-- Full BOM_TBL Data (253 rows)
-- Run after 02_data.sql

USE SCHEMA BOM.BOM4;

-- Clear existing sample data and insert full dataset
TRUNCATE TABLE IF EXISTS BOM_TBL;

INSERT INTO BOM_TBL (OPTION_ID, SYSTEM_NM, SUBSYSTEM_NM, COMPONENT_GROUP, OPTION_NM, COST_USD, WEIGHT_LBS, SOURCE_COUNTRY, PERFORMANCE_CATEGORY, PERFORMANCE_SCORE, DESCRIPTION, OPTION_TIER) VALUES
('1', 'Cab', 'Cab Structure', 'Cab Type', 'Day Cab Standard', 0, 1200, 'USA', 'Comfort', 1, 'Basic day cab for regional and local operations. No sleeping quarters.', 'ENTRY'),
('2', 'Cab', 'Cab Structure', 'Cab Type', 'Low-Entry Day Cab', 1500, 1250, 'USA', 'Comfort', 1.5, 'Lower step-in height.', 'STANDARD'),
('3', 'Cab', 'Cab Structure', 'Cab Type', 'Day Cab Extended', 2500, 1350, 'USA', 'Comfort', 2.5, 'Extended day cab with additional storage and legroom.', 'STANDARD'),
('4', 'Cab', 'Cab Structure', 'Cab Type', 'Sleeper 48-inch Flat Roof', 6500, 1800, 'USA', 'Comfort', 3, 'Compact sleeper for budget-conscious fleets.', 'STANDARD'),
('5', 'Cab', 'Cab Structure', 'Cab Type', 'Crew Cab 4-Door', 8500, 1650, 'USA', 'Comfort', 3.5, 'Four-door crew cab for vocational.', 'STANDARD'),
('6', 'Cab', 'Cab Structure', 'Cab Type', 'Sleeper 72-inch Mid Roof', 12000, 2200, 'USA', 'Comfort', 4.5, 'Mid-roof sleeper with stand-up height.', 'PREMIUM'),
('7', 'Cab', 'Cab Structure', 'Cab Type', 'Sleeper 80-inch Raised Roof', 22000, 2600, 'USA', 'Comfort', 5, 'Full-height raised roof sleeper.', 'FLAGSHIP'),
('8', 'Cab', 'Climate Control', 'HVAC System', 'Manual Climate Control', 0, 45, 'Mexico', 'Comfort', 1, 'Basic manual HVAC with heater and A/C.', 'ENTRY'),
('9', 'Cab', 'Climate Control', 'HVAC System', 'Automatic Climate Control', 1200, 52, 'USA', 'Comfort', 2, 'Single-zone automatic temperature control.', 'STANDARD'),
('10', 'Cab', 'Climate Control', 'HVAC System', 'High-Capacity A/C', 1800, 58, 'USA', 'Comfort', 2.5, 'Extra cooling capacity.', 'STANDARD'),
('11', 'Cab', 'Climate Control', 'HVAC System', 'Dual-Zone Climate Control', 2800, 65, 'USA', 'Comfort', 3.5, 'Independent driver/passenger temperature zones.', 'PREMIUM'),
('12', 'Cab', 'Climate Control', 'HVAC System', 'APU Climate System', 4200, 75, 'USA', 'Comfort', 4, 'Idle-free APU climate.', 'PREMIUM'),
('13', 'Cab', 'Climate Control', 'HVAC System', 'Tri-Zone Premium Climate', 5500, 85, 'USA', 'Comfort', 5, 'Three-zone control including sleeper.', 'FLAGSHIP'),
('14', 'Cab', 'Interior', 'Interior Trim', 'Vinyl Work Trim', 0, 120, 'Mexico', 'Comfort', 1, 'Durable vinyl surfaces for work applications.', 'ENTRY'),
('15', 'Cab', 'Interior', 'Interior Trim', 'Heavy-Duty Vinyl Plus', 450, 125, 'Mexico', 'Comfort', 2, 'Enhanced work-grade vinyl.', 'STANDARD'),
('16', 'Cab', 'Interior', 'Interior Trim', 'Cloth Standard Trim', 800, 135, 'USA', 'Comfort', 2.5, 'Standard cloth upholstery with vinyl accents.', 'STANDARD'),
('17', 'Cab', 'Interior', 'Interior Trim', 'Premium Cloth Package', 2200, 150, 'USA', 'Comfort', 3.5, 'Upgraded cloth with leather steering wheel.', 'PREMIUM'),
('18', 'Cab', 'Interior', 'Interior Trim', 'Leather Sport Trim', 5500, 160, 'USA', 'Comfort', 4, 'Sporty leather with contrast stitching.', 'PREMIUM'),
('19', 'Cab', 'Interior', 'Interior Trim', 'Executive Leather Interior', 8500, 175, 'USA', 'Comfort', 5, 'Full leather surfaces with wood-grain accents.', 'FLAGSHIP'),
('20', 'Cab', 'Interior', 'Seating Configuration', 'Fixed Base Driver Seat', 0, 85, 'Mexico', 'Comfort', 1, 'Fixed position driver seat with basic adjustment.', 'ENTRY'),
('21', 'Cab', 'Interior', 'Seating Configuration', 'Air-Ride Driver Seat', 1500, 95, 'USA', 'Comfort', 2, 'Air-suspension seat with lumbar support.', 'STANDARD'),
('22', 'Cab', 'Interior', 'Seating Configuration', 'Dual Air-Ride Team Seats', 2800, 190, 'USA', 'Comfort', 2.5, 'Matched team seating.', 'STANDARD'),
('23', 'Cab', 'Interior', 'Seating Configuration', 'Premium Air-Ride with Heat', 3200, 105, 'USA', 'Comfort', 3.5, 'Heated/ventilated air-ride seat.', 'PREMIUM'),
('24', 'Cab', 'Interior', 'Seating Configuration', 'Sport Bucket Seats', 4500, 115, 'Germany', 'Comfort', 4, 'Performance-oriented bucket seats.', 'PREMIUM'),
('25', 'Cab', 'Interior', 'Seating Configuration', 'Executive Massaging Seat', 6500, 125, 'USA', 'Comfort', 5, 'Full massage system, cooling/heating.', 'FLAGSHIP'),
('26', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'No Sleeper (Day Cab)', 0, 0, 'USA', 'Comfort', 1, 'Day cab configuration - no sleeping quarters.', 'ENTRY'),
('27', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'Single Bunk 36-inch', 3500, 180, 'USA', 'Comfort', 2, 'Single bunk for solo drivers.', 'STANDARD'),
('28', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'Double Bunk 42-inch', 6500, 280, 'USA', 'Comfort', 3, 'Team driver double bunk.', 'PREMIUM'),
('29', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'King-Size Single 48-inch', 9500, 350, 'USA', 'Comfort', 4, 'Extra-wide single bunk with premium mattress.', 'FLAGSHIP'),
('30', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'Studio Sleeper 60-inch', 15000, 420, 'USA', 'Comfort', 5, 'Studio-style living space.', 'FLAGSHIP'),
('31', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'No Sleeper Amenities', 0, 0, 'USA', 'Comfort', 1, 'Day cab or basic sleeper - no amenities.', 'ENTRY'),
('32', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'Standard Sleeper Package', 2500, 85, 'USA', 'Comfort', 2, 'Overhead storage, reading lights, DC outlets.', 'STANDARD'),
('33', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'Entertainment Package', 3500, 110, 'USA', 'Comfort', 3, 'TV, sound system, WiFi ready.', 'STANDARD'),
('34', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'Premium Sleeper Package', 5500, 145, 'USA', 'Comfort', 4, 'Microwave, larger fridge, TV mount.', 'PREMIUM'),
('35', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'Luxury Living Package', 12000, 220, 'USA', 'Comfort', 5, 'Full kitchen, diesel generator, smart TV.', 'FLAGSHIP'),
('36', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Standard Fifth Wheel', 0, 210, 'USA', 'Hauling', 1, 'Standard for light-medium loads.', 'ENTRY'),
('37', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Low-Profile Fifth Wheel', 1500, 240, 'USA', 'Hauling', 1.5, 'Lower deck height option.', 'STANDARD'),
('38', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Sliding Fifth Wheel', 2200, 280, 'USA', 'Hauling', 2.5, 'Manual slide for weight distribution.', 'STANDARD'),
('39', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Lightweight Aluminum Fifth', 3500, 180, 'USA', 'Hauling', 3, 'Weight-saving aluminum design.', 'STANDARD'),
('40', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Air-Slide Fifth Wheel', 4500, 320, 'USA', 'Hauling', 3.5, 'Air-powered sliding mechanism.', 'PREMIUM'),
('41', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Compensating Fifth Wheel', 5500, 350, 'USA', 'Hauling', 4.5, 'Self-aligning for uneven loads.', 'PREMIUM'),
('42', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Heavy-Haul Fifth Wheel', 8500, 480, 'USA', 'Hauling', 5, 'Maximum GCWR capability.', 'FLAGSHIP'),
('43', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Standard Steel Frame', 0, 2800, 'USA', 'Durability', 1, 'Standard duty rating.', 'ENTRY'),
('44', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Reinforced Crossmembers', 2500, 3100, 'USA', 'Durability', 1.5, 'Extra crossmember bracing.', 'STANDARD'),
('45', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Heavy-Duty Steel Frame', 3500, 3200, 'USA', 'Durability', 2.5, 'Reinforced frame rails.', 'STANDARD'),
('46', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Corrosion-Resistant Frame', 5500, 3400, 'USA', 'Durability', 3, 'Galvanized frame rails.', 'PREMIUM'),
('47', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Extra Heavy-Duty Frame', 7500, 3800, 'USA', 'Durability', 3.5, 'Full-length reinforcement.', 'PREMIUM'),
('48', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Aluminum Hybrid Frame', 12000, 2400, 'USA', 'Durability', 4.5, 'Lightweight aluminum frame.', 'PREMIUM'),
('49', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Vocational Heavy-Haul Frame', 14000, 4500, 'USA', 'Durability', 5, 'Max RBM rating.', 'FLAGSHIP'),
('50', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Ultra-Short 156-inch', 100, 0, 'USA', 'Hauling', 1.5, 'Minimum wheelbase for maneuverability.', 'ENTRY'),
('51', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Short Wheelbase 170-inch', 0, 0, 'USA', 'Hauling', 1, 'Urban maneuvering.', 'ENTRY'),
('52', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Custom 195-inch', 400, 25, 'USA', 'Hauling', 2.5, 'Compact custom wheelbase.', 'STANDARD'),
('53', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Standard Wheelbase 210-inch', 800, 45, 'USA', 'Hauling', 3, 'General freight.', 'STANDARD'),
('54', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Mid-Length 228-inch', 1200, 65, 'USA', 'Hauling', 3.5, 'Versatile mid-length wheelbase.', 'STANDARD'),
('55', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Extended Wheelbase 245-inch', 1800, 95, 'USA', 'Hauling', 4.5, 'Larger sleepers.', 'PREMIUM'),
('56', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Long Wheelbase 280-inch', 3500, 150, 'USA', 'Hauling', 5, 'Heavy haul.', 'FLAGSHIP'),
('57', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Behind Cab 5-Gallon', 0, 25, 'USA', 'Emissions', 1, 'Compact DEF tank.', 'ENTRY'),
('58', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Frame-Mount 13-Gallon', 450, 35, 'USA', 'Emissions', 2, 'Standard frame-mounted.', 'STANDARD'),
('59', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Integrated DEF 10-Gallon', 650, 30, 'USA', 'Emissions', 2.5, 'Frame-integrated DEF tank.', 'STANDARD'),
('60', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Under-Cab 15-Gallon', 750, 40, 'USA', 'Emissions', 3.5, 'Space-saving under-cab mount.', 'STANDARD'),
('61', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Saddle-Mount 18-Gallon', 950, 48, 'USA', 'Emissions', 4, 'Large capacity heated.', 'PREMIUM'),
('62', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Dual Tank 26-Gallon', 1800, 72, 'USA', 'Emissions', 5, 'Maximum DEF capacity.', 'FLAGSHIP'),
('63', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Single 100-Gallon Aluminum', 0, 85, 'USA', 'Economy', 1, '600-mile range.', 'ENTRY'),
('64', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Single 125-Gallon Steel', 800, 145, 'USA', 'Economy', 1.5, 'Steel tank option.', 'STANDARD'),
('65', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Dual 100-Gallon Aluminum', 1800, 170, 'USA', 'Economy', 2.5, '1200-mile range.', 'STANDARD'),
('66', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Single 150-Gallon Aluminum', 2200, 128, 'USA', 'Economy', 3, '900-mile range single tank.', 'STANDARD'),
('67', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Dual 150-Gallon Aluminum', 3200, 255, 'USA', 'Economy', 3.5, '1800-mile range.', 'PREMIUM'),
('68', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Dual 200-Gallon Aluminum', 5500, 340, 'USA', 'Economy', 4.5, '2400-mile range.', 'FLAGSHIP'),
('69', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Tri-Tank 225-Gallon', 7500, 395, 'USA', 'Economy', 5, 'Three-tank maximum range.', 'FLAGSHIP'),
('70', 'Electrical', 'Electronics', 'ADAS Features', 'Basic Safety Suite', 0, 15, 'Japan', 'Safety', 1, 'Basic ABS and stability control.', 'ENTRY'),
('71', 'Electrical', 'Electronics', 'ADAS Features', 'Rear Cross-Traffic Alert', 2200, 20, 'Japan', 'Safety', 2, 'Backing collision prevention.', 'STANDARD'),
('72', 'Electrical', 'Electronics', 'ADAS Features', 'Standard ADAS Package', 3500, 28, 'USA', 'Safety', 2.5, 'Forward collision warning, lane departure.', 'STANDARD'),
('73', 'Electrical', 'Electronics', 'ADAS Features', 'Commercial ADAS Plus', 5500, 35, 'USA', 'Safety', 3.5, 'Mid-tier safety package.', 'STANDARD'),
('74', 'Electrical', 'Electronics', 'ADAS Features', 'Advanced ADAS Package', 7500, 42, 'USA', 'Safety', 4, 'Auto emergency braking, adaptive cruise.', 'PREMIUM'),
('75', 'Electrical', 'Electronics', 'ADAS Features', 'Full ADAS Highway Pilot', 15000, 65, 'USA', 'Safety', 5, 'Level 2 highway pilot, 360-degree sensors.', 'FLAGSHIP'),
('76', 'Electrical', 'Electronics', 'Telematics', 'Basic GPS Tracking', 0, 2, 'China', 'Economy', 1, 'Simple GPS location tracking.', 'ENTRY'),
('77', 'Electrical', 'Electronics', 'Telematics', 'Fleet Telematics Standard', 1500, 5, 'USA', 'Economy', 2, 'GPS, ELD compliance, fuel tracking.', 'STANDARD'),
('78', 'Electrical', 'Electronics', 'Telematics', 'Fuel Coach System', 2000, 4, 'USA', 'Economy', 2.5, 'Real-time fuel coaching.', 'STANDARD'),
('79', 'Electrical', 'Electronics', 'Telematics', 'Video Telematics', 2500, 6, 'USA', 'Economy', 3.5, 'Dash cam integration.', 'STANDARD'),
('80', 'Electrical', 'Electronics', 'Telematics', 'Advanced Fleet Management', 3500, 8, 'USA', 'Economy', 4, 'Real-time diagnostics, predictive maintenance.', 'PREMIUM'),
('81', 'Electrical', 'Electronics', 'Telematics', 'Enterprise Telematics Suite', 6500, 12, 'USA', 'Economy', 5, 'Full fleet intelligence, route optimization.', 'FLAGSHIP'),
('82', 'Electrical', 'Lighting', 'Headlights', 'Halogen Headlights', 0, 8, 'Mexico', 'Safety', 1, 'Standard halogen sealed beam.', 'ENTRY'),
('83', 'Electrical', 'Lighting', 'Headlights', 'Fog Light Package', 450, 5, 'USA', 'Safety', 2, 'Auxiliary fog lights.', 'STANDARD'),
('84', 'Electrical', 'Lighting', 'Headlights', 'Projector Halogen Lights', 650, 12, 'USA', 'Safety', 2.5, 'Projector-style with improved focus.', 'STANDARD'),
('85', 'Electrical', 'Lighting', 'Headlights', 'Bi-LED Projector System', 1500, 9, 'Japan', 'Safety', 3.5, 'Mid-range LED system.', 'STANDARD'),
('86', 'Electrical', 'Lighting', 'Headlights', 'LED Headlight System', 2200, 6, 'USA', 'Safety', 4, 'Full LED headlights and markers.', 'PREMIUM'),
('87', 'Electrical', 'Lighting', 'Headlights', 'Adaptive LED Matrix Lights', 4500, 9, 'USA', 'Safety', 5, 'Matrix LED with auto high beam.', 'FLAGSHIP'),
('88', 'Electrical', 'Power Generation', 'Alternator', '160 Amp Alternator', 0, 28, 'Mexico', 'Power', 1, 'Standard 160A for basic loads.', 'ENTRY'),
('89', 'Electrical', 'Power Generation', 'Alternator', '200 Amp High-Efficiency', 650, 32, 'USA', 'Power', 2, 'Efficient mid-range alternator.', 'STANDARD'),
('90', 'Electrical', 'Power Generation', 'Alternator', '250 Amp Alternator', 850, 35, 'USA', 'Power', 2.5, 'High-output for accessories.', 'STANDARD'),
('91', 'Electrical', 'Power Generation', 'Alternator', '280 Amp Brushless', 1500, 40, 'USA', 'Power', 3.5, 'Brushless high-output.', 'STANDARD'),
('92', 'Electrical', 'Power Generation', 'Alternator', '320 Amp Dual Alternator', 2200, 65, 'USA', 'Power', 4, 'Dual alternator for heavy demands.', 'PREMIUM'),
('93', 'Electrical', 'Power Generation', 'Alternator', '400 Amp Triple Alternator', 4500, 95, 'USA', 'Power', 5, 'Maximum electrical capacity.', 'FLAGSHIP'),
('94', 'Electrical', 'Power Generation', 'Battery System', 'Dual 12V Standard Batteries', 0, 130, 'USA', 'Power', 1, 'Standard dual Group 31, 1900 CCA.', 'ENTRY'),
('95', 'Electrical', 'Power Generation', 'Battery System', 'Triple 12V Heavy-Duty', 450, 195, 'USA', 'Power', 2, 'Three Group 31, 2850 CCA.', 'STANDARD'),
('96', 'Electrical', 'Power Generation', 'Battery System', 'Cold-Weather Battery Pack', 650, 210, 'USA', 'Power', 2.5, 'High-CCA cold weather.', 'STANDARD'),
('97', 'Electrical', 'Power Generation', 'Battery System', 'Dual AGM Premium', 850, 150, 'USA', 'Power', 3.5, 'Premium AGM dual batteries.', 'STANDARD'),
('98', 'Electrical', 'Power Generation', 'Battery System', 'Quad AGM Battery System', 1200, 240, 'USA', 'Power', 4, 'Four AGM batteries with isolator.', 'PREMIUM'),
('99', 'Electrical', 'Power Generation', 'Battery System', 'Lithium-Ion Auxiliary', 3500, 85, 'USA', 'Power', 5, 'Lithium auxiliary bank, 10-year life.', 'FLAGSHIP'),
('100', 'Engine', 'Cooling System', 'Fan Assembly', 'Belt-Drive Fixed Fan', 0, 45, 'USA', 'Cooling', 1, 'Simple belt-driven fan.', 'ENTRY'),
('101', 'Engine', 'Cooling System', 'Fan Assembly', 'High-CFM Fixed Fan', 350, 50, 'USA', 'Cooling', 2, 'High-airflow fixed fan.', 'STANDARD'),
('102', 'Engine', 'Cooling System', 'Fan Assembly', 'Viscous Clutch Fan', 650, 58, 'USA', 'Cooling', 2.5, 'Temperature-controlled viscous clutch.', 'STANDARD'),
('103', 'Engine', 'Cooling System', 'Fan Assembly', 'Electric Fan with Clutch', 1800, 72, 'USA', 'Cooling', 3.5, 'Electronically-controlled fan.', 'PREMIUM'),
('104', 'Engine', 'Cooling System', 'Fan Assembly', 'Dual Electric Fans', 2500, 65, 'USA', 'Cooling', 4, 'Redundant dual fan system.', 'PREMIUM'),
('105', 'Engine', 'Cooling System', 'Fan Assembly', 'Variable-Speed Electric Fan', 3500, 85, 'USA', 'Cooling', 5, 'Infinitely variable fan speed.', 'FLAGSHIP'),
('106', 'Engine', 'Cooling System', 'Radiator', 'Standard Aluminum Radiator', 0, 95, 'USA', 'Cooling', 1, 'Standard capacity.', 'ENTRY'),
('107', 'Engine', 'Cooling System', 'Radiator', 'High-Capacity Radiator', 1200, 115, 'China', 'Cooling', 2, '20% increased capacity.', 'STANDARD'),
('108', 'Engine', 'Cooling System', 'Radiator', 'Aluminum-Brass Radiator', 1800, 125, 'China', 'Cooling', 2.5, 'Hybrid aluminum-brass design.', 'STANDARD'),
('109', 'Engine', 'Cooling System', 'Radiator', 'Extended Core Radiator', 2000, 130, 'China', 'Cooling', 3.5, 'Extended core for moderate duty.', 'STANDARD'),
('110', 'Engine', 'Cooling System', 'Radiator', 'Heavy-Duty Cooling Package', 2800, 145, 'China', 'Cooling', 4, 'Oversized with auxiliary cooler.', 'PREMIUM'),
('111', 'Engine', 'Cooling System', 'Radiator', 'Extreme Duty Cooling', 5500, 185, 'China', 'Cooling', 5, 'Maximum cooling capacity.', 'FLAGSHIP'),
('112', 'Engine', 'Emissions System', 'DEF System', 'Standard SCR System', 0, 145, 'USA', 'Emissions', 1, 'Basic SCR, EPA 2017 compliant.', 'ENTRY'),
('113', 'Engine', 'Emissions System', 'DEF System', 'Enhanced SCR System', 1500, 165, 'USA', 'Emissions', 2, 'Improved DEF dosing.', 'STANDARD'),
('114', 'Engine', 'Emissions System', 'DEF System', 'Low-Consumption SCR', 2500, 175, 'USA', 'Emissions', 2.5, 'Reduced DEF consumption.', 'STANDARD'),
('115', 'Engine', 'Emissions System', 'DEF System', 'Advanced Emissions Package', 3500, 195, 'USA', 'Emissions', 3.5, 'Integrated DPF/SCR, near-zero NOx.', 'PREMIUM'),
('116', 'Engine', 'Emissions System', 'DEF System', 'Premium Emissions Control', 4500, 210, 'Germany', 'Emissions', 4, 'Premium emission system.', 'PREMIUM'),
('117', 'Engine', 'Emissions System', 'DEF System', 'Ultra-Clean Emissions', 6500, 225, 'USA', 'Emissions', 5, 'CARB compliant, low-emission zone ready.', 'FLAGSHIP'),
('118', 'Engine', 'Engine Block', 'Engine Displacement', '6.7L Medium-Duty Diesel', 0, 1100, 'USA', 'Power', 1, 'Compact diesel, best fuel economy.', 'ENTRY'),
('119', 'Engine', 'Engine Block', 'Engine Displacement', '7.2L Regional Diesel', 1500, 1050, 'USA', 'Power', 1.5, 'Optimized for regional routes.', 'STANDARD'),
('120', 'Engine', 'Engine Block', 'Engine Displacement', '9L Mid-Range Diesel', 4500, 1250, 'USA', 'Power', 2, 'Balance of power and efficiency.', 'STANDARD'),
('121', 'Engine', 'Engine Block', 'Engine Displacement', '10L Balanced Diesel', 5500, 1300, 'USA', 'Power', 2.5, 'Mid-size balanced engine.', 'STANDARD'),
('122', 'Engine', 'Engine Block', 'Engine Displacement', '11L Mid-Plus Diesel', 6500, 1350, 'USA', 'Power', 3.5, 'Versatile mid-range power.', 'PREMIUM'),
('123', 'Engine', 'Engine Block', 'Engine Displacement', '13L Class 8 Diesel', 9500, 1450, 'USA', 'Power', 4, 'Industry-standard Class 8 engine.', 'PREMIUM'),
('124', 'Engine', 'Engine Block', 'Engine Displacement', '15L Heavy-Haul Diesel', 16000, 1650, 'USA', 'Power', 4.5, 'Maximum displacement.', 'FLAGSHIP'),
('125', 'Engine', 'Engine Block', 'Engine Displacement', '16L Maximum Diesel', 22000, 1800, 'USA', 'Power', 5, 'Largest available displacement.', 'FLAGSHIP'),
('126', 'Engine', 'Engine Block', 'Power Rating', '260 HP / 660 lb-ft', 0, 0, 'USA', 'Power', 1, 'Entry-level power for light loads.', 'ENTRY'),
('127', 'Engine', 'Engine Block', 'Power Rating', '300 HP / 860 lb-ft Regional', 1200, 5, 'USA', 'Power', 1.5, 'Regional delivery power.', 'STANDARD'),
('128', 'Engine', 'Engine Block', 'Power Rating', '350 HP / 1150 lb-ft', 2500, 15, 'USA', 'Power', 2, 'Standard power for general freight.', 'STANDARD'),
('129', 'Engine', 'Engine Block', 'Power Rating', '380 HP / 1250 lb-ft Fleet', 3500, 18, 'USA', 'Power', 2.5, 'Fleet-optimized power.', 'STANDARD'),
('130', 'Engine', 'Engine Block', 'Power Rating', '400 HP / 1400 lb-ft Mid-Range', 4500, 20, 'USA', 'Power', 3, 'Fleet workhorse power.', 'PREMIUM'),
('131', 'Engine', 'Engine Block', 'Power Rating', '450 HP / 1650 lb-ft', 6500, 25, 'USA', 'Power', 3.5, 'High-output for heavy loads.', 'PREMIUM'),
('132', 'Engine', 'Engine Block', 'Power Rating', '500 HP / 1750 lb-ft Heavy', 8500, 32, 'USA', 'Power', 4, 'Heavy-duty power rating.', 'PREMIUM'),
('133', 'Engine', 'Engine Block', 'Power Rating', '565 HP / 1850 lb-ft', 12000, 40, 'USA', 'Power', 4.5, 'Maximum power for heavy haul.', 'FLAGSHIP'),
('134', 'Engine', 'Engine Block', 'Power Rating', '605 HP / 2050 lb-ft Maximum', 18000, 55, 'USA', 'Power', 5, 'Ultimate heavy haul power.', 'FLAGSHIP'),
('135', 'Engine', 'Engine Block', 'Turbocharger', 'Single Fixed-Geometry Turbo', 0, 45, 'Japan', 'Power', 1, 'Simple fixed turbo.', 'ENTRY'),
('136', 'Engine', 'Engine Block', 'Turbocharger', 'Variable Geometry Turbo', 2200, 52, 'USA', 'Power', 2, 'VGT, reduced turbo lag.', 'STANDARD'),
('137', 'Engine', 'Engine Block', 'Turbocharger', 'Twin-Scroll VGT', 4500, 68, 'USA', 'Power', 2.5, 'Better low-end torque.', 'PREMIUM'),
('138', 'Engine', 'Engine Block', 'Turbocharger', 'Electric Assist Turbo', 6500, 58, 'Germany', 'Power', 3.5, 'E-turbo for instant response.', 'PREMIUM'),
('139', 'Engine', 'Engine Block', 'Turbocharger', 'Compound Turbo System', 8500, 95, 'USA', 'Power', 4, 'Series turbos, max boost.', 'FLAGSHIP'),
('140', 'Engine', 'Engine Block', 'Turbocharger', 'Twin VGT System', 12000, 85, 'Germany', 'Power', 5, 'Dual variable geometry turbos.', 'FLAGSHIP'),
('141', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Exhaust Brake Only', 0, 25, 'USA', 'Safety', 1, 'Basic exhaust brake.', 'ENTRY'),
('142', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Engine Compression Brake', 2500, 45, 'USA', 'Safety', 2, 'Jake brake system.', 'STANDARD'),
('143', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Two-Stage Engine Brake', 3500, 55, 'USA', 'Safety', 2.5, 'Variable two-stage jake.', 'STANDARD'),
('144', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Integrated Retarder System', 5500, 85, 'USA', 'Safety', 3.5, 'Engine brake plus driveline retarder.', 'PREMIUM'),
('145', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Three-Stage Engine Brake', 6500, 75, 'USA', 'Safety', 4, 'Three-level braking.', 'PREMIUM'),
('146', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Full Retarder Package', 9500, 125, 'USA', 'Safety', 5, 'Maximum braking.', 'FLAGSHIP'),
('147', 'Front Axle', 'Axle Assembly', 'Axle Rating', '12,000 lb Front Axle', 0, 550, 'USA', 'Hauling', 1, 'Light-duty front axle.', 'ENTRY'),
('148', 'Front Axle', 'Axle Assembly', 'Axle Rating', '13,200 lb Front Axle', 650, 580, 'USA', 'Hauling', 1.5, 'Light-medium front axle.', 'STANDARD'),
('149', 'Front Axle', 'Axle Assembly', 'Axle Rating', '14,600 lb Front Axle', 1200, 620, 'USA', 'Hauling', 2.5, 'Standard Class 8 front axle.', 'STANDARD'),
('150', 'Front Axle', 'Axle Assembly', 'Axle Rating', '16,000 lb Front Axle', 2000, 680, 'USA', 'Hauling', 3, 'Medium-heavy front axle.', 'STANDARD'),
('151', 'Front Axle', 'Axle Assembly', 'Axle Rating', '18,000 lb Front Axle', 2800, 720, 'USA', 'Hauling', 3.5, 'Heavy-duty front axle.', 'PREMIUM'),
('152', 'Front Axle', 'Axle Assembly', 'Axle Rating', '20,000 lb Front Axle', 4200, 780, 'USA', 'Hauling', 4.5, 'Vocational heavy front.', 'PREMIUM'),
('153', 'Front Axle', 'Axle Assembly', 'Axle Rating', '22,000 lb Front Axle', 5500, 850, 'USA', 'Hauling', 5, 'Maximum front axle rating.', 'FLAGSHIP'),
('154', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Drum Brakes Standard', 0, 180, 'USA', 'Safety', 1, 'Conventional drum brakes.', 'ENTRY'),
('155', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Wide Drum Brakes', 350, 200, 'China', 'Safety', 2, 'Wider drums, more area.', 'STANDARD'),
('156', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Ventilated Drum Brakes', 450, 190, 'China', 'Safety', 2.5, 'Improved cooling drums.', 'STANDARD'),
('157', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Enhanced Drum Brakes', 650, 195, 'China', 'Safety', 3.5, 'Larger drum brakes with improved cooling.', 'STANDARD'),
('158', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Air Disc Brakes', 2800, 165, 'China', 'Safety', 4, 'Shorter stopping, fade resistance.', 'PREMIUM'),
('159', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Premium Air Disc System', 5500, 175, 'China', 'Safety', 5, 'High-performance disc brakes.', 'FLAGSHIP'),
('160', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Tapered Leaf Spring', 0, 320, 'USA', 'Comfort', 1, 'Traditional leaf springs.', 'ENTRY'),
('161', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Heavy-Duty Leaf Spring', 650, 340, 'USA', 'Comfort', 2, 'Reinforced leaf springs.', 'STANDARD'),
('162', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Comfort-Ride Springs', 850, 295, 'USA', 'Comfort', 2.5, 'Optimized spring rate.', 'STANDARD'),
('163', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Parabolic Leaf Spring', 1200, 280, 'USA', 'Comfort', 3.5, 'Improved ride, lighter weight.', 'STANDARD'),
('164', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Air-Ride Front Suspension', 4500, 350, 'USA', 'Comfort', 4, 'Superior ride quality.', 'PREMIUM'),
('165', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Independent Air Suspension', 9500, 420, 'USA', 'Comfort', 5, 'Premium ride and handling.', 'FLAGSHIP'),
('166', 'Front Axle', 'Steering', 'Steering Gear', 'Manual Steering Gear', 0, 85, 'USA', 'Safety', 1, 'Basic manual power steering.', 'ENTRY'),
('167', 'Front Axle', 'Steering', 'Steering Gear', 'Power Steering Standard', 950, 95, 'USA', 'Safety', 2, 'Hydraulic power steering.', 'STANDARD'),
('168', 'Front Axle', 'Steering', 'Steering Gear', 'Heavy-Duty Power Steering', 1800, 100, 'Mexico', 'Safety', 3, 'High-capacity power steering.', 'STANDARD'),
('169', 'Front Axle', 'Steering', 'Steering Gear', 'Variable-Assist Steering', 2500, 105, 'Mexico', 'Safety', 4, 'Speed-sensitive power assist.', 'PREMIUM'),
('170', 'Front Axle', 'Steering', 'Steering Gear', 'Electronic Power Steering', 5500, 75, 'Mexico', 'Safety', 5, 'Lane-keeping assist compatible.', 'FLAGSHIP'),
('171', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Standard Drum Brakes', 0, 360, 'USA', 'Safety', 1, 'Standard S-cam drum brakes.', 'ENTRY'),
('172', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Wide-Track Drum Brakes', 550, 400, 'China', 'Safety', 2, 'Wider track drums.', 'STANDARD'),
('173', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Extended-Life Drum Brakes', 850, 385, 'China', 'Safety', 2.5, 'Automatic adjusters.', 'STANDARD'),
('174', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Heavy-Duty Drum Plus', 1200, 395, 'China', 'Safety', 3.5, 'Enhanced heavy-duty drums.', 'STANDARD'),
('175', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Air Disc Brakes Rear', 4500, 320, 'China', 'Safety', 4, 'Superior stopping power.', 'PREMIUM'),
('176', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Full Air Disc System', 8500, 340, 'China', 'Safety', 5, 'Maximum performance.', 'FLAGSHIP'),
('177', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '2.85:1 Standard Ratio', 0, 0, 'USA', 'Economy', 2, 'Balanced for general freight.', 'STANDARD'),
('178', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '2.47:1 Economy Ratio', 150, 0, 'USA', 'Economy', 1, 'Tall gearing for max fuel economy.', 'ENTRY'),
('179', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '3.08:1 Balanced Ratio', 200, 0, 'USA', 'Economy', 2.5, 'Balanced gearing option.', 'STANDARD'),
('180', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '3.25:1 Performance Ratio', 350, 0, 'USA', 'Economy', 3.5, 'Better acceleration, hilly terrain.', 'PREMIUM'),
('181', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '3.55:1 Vocational Ratio', 450, 0, 'USA', 'Economy', 4, 'Vocational applications.', 'PREMIUM'),
('182', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '3.73:1 Heavy-Haul Ratio', 650, 0, 'USA', 'Economy', 5, 'Max pulling power.', 'FLAGSHIP'),
('183', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '4x2 Single Drive Axle', 0, 0, 'USA', 'Hauling', 1, 'Single drive axle, best economy.', 'ENTRY'),
('184', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '6x2 Tag Axle', 1800, 380, 'USA', 'Hauling', 2, 'Tag axle configuration.', 'STANDARD'),
('185', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '6x2 Pusher Axle', 2500, 450, 'USA', 'Hauling', 3, 'Single drive with liftable pusher.', 'STANDARD'),
('186', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '6x4 Tandem Drive', 5500, 850, 'USA', 'Hauling', 4, 'Traditional tandem drive.', 'PREMIUM'),
('187', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '6x6 All-Wheel Drive', 15000, 1200, 'USA', 'Hauling', 5, 'Full AWD for severe conditions.', 'FLAGSHIP'),
('188', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Basic ABS Only', 0, 25, 'USA', 'Safety', 1, 'Standard ABS.', 'ENTRY'),
('189', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'ABS with Traction Control', 1500, 35, 'USA', 'Safety', 2, 'Improved starts in slippery conditions.', 'STANDARD'),
('190', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Limited-Slip Differential', 1800, 38, 'USA', 'Safety', 2.5, 'Mechanical limited slip.', 'STANDARD'),
('191', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Differential Lock System', 2500, 42, 'USA', 'Safety', 3.5, 'Manual diff lock option.', 'STANDARD'),
('192', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Advanced Traction System', 3500, 48, 'USA', 'Safety', 4, 'Full stability, rollover prevention.', 'PREMIUM'),
('193', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Full Electronic Stability', 6500, 65, 'USA', 'Safety', 5, 'Complete stability package.', 'FLAGSHIP'),
('194', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Spring Rear Suspension', 0, 680, 'USA', 'Comfort', 1, 'Traditional multi-leaf springs.', 'ENTRY'),
('195', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Vocational Spring Package', 1800, 720, 'USA', 'Comfort', 2, 'Heavy-duty vocational springs.', 'STANDARD'),
('196', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Air-Ride Rear Standard', 3500, 580, 'USA', 'Comfort', 2.5, 'Standard air-ride suspension.', 'STANDARD'),
('197', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Low-Ride Air Suspension', 4500, 600, 'Germany', 'Comfort', 3.5, 'Lowered ride height air system.', 'PREMIUM'),
('198', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Premium Air-Ride System', 6500, 620, 'USA', 'Comfort', 4, 'Adjustable ride height.', 'PREMIUM'),
('199', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Elite Air-Ride Package', 12000, 680, 'USA', 'Comfort', 5, 'Cab-coupled system.', 'FLAGSHIP'),
('200', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Standard Bias-Ply Tires', 0, 420, 'China', 'Economy', 1, 'Budget tires for light duty.', 'ENTRY'),
('201', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Standard Radial Tires', 1200, 380, 'USA', 'Economy', 2, 'Quality radial tires.', 'STANDARD'),
('202', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'All-Season Regional Tires', 1800, 365, 'USA', 'Economy', 2.5, 'Regional all-season.', 'STANDARD'),
('203', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Low-Rolling-Resistance Tires', 2800, 350, 'USA', 'Economy', 3.5, 'SmartWay verified, 3-5% fuel savings.', 'PREMIUM'),
('204', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Wide-Base Single Tires', 3500, 290, 'Japan', 'Economy', 4, 'Super singles for fuel savings.', 'PREMIUM'),
('205', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Premium Fuel-Max Tires', 4500, 340, 'USA', 'Economy', 5, 'Best-in-class fuel economy.', 'FLAGSHIP'),
('206', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Steel Hub-Pilot Wheels', 0, 680, 'USA', 'Economy', 1, 'Standard steel wheels.', 'ENTRY'),
('207', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Steel Disc Wheels', 450, 620, 'USA', 'Economy', 2, 'Improved steel disc wheels.', 'STANDARD'),
('208', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Aluminum Disc Wheels', 1500, 480, 'USA', 'Economy', 2.5, 'Mid-range aluminum.', 'STANDARD'),
('209', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Aluminum Wheels Standard', 2200, 420, 'China', 'Economy', 3.5, 'Forged aluminum, weight savings.', 'PREMIUM'),
('210', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Premium Polished Aluminum', 4500, 380, 'China', 'Economy', 4, 'Mirror-polished, show quality.', 'FLAGSHIP'),
('211', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Forged Racing Wheels', 6500, 340, 'Germany', 'Economy', 5, 'Lightweight forged design.', 'FLAGSHIP'),
('212', 'Safety', 'Active Safety', 'Stability Control', 'Basic ABS System', 0, 45, 'USA', 'Safety', 1, 'Standard 4-channel ABS.', 'ENTRY'),
('213', 'Safety', 'Active Safety', 'Stability Control', 'Enhanced ABS Plus', 950, 50, 'USA', 'Safety', 2, 'ABS with enhanced sensors.', 'STANDARD'),
('214', 'Safety', 'Active Safety', 'Stability Control', 'Roll Stability Control', 1800, 55, 'USA', 'Safety', 2.5, 'RSC prevents rollover.', 'STANDARD'),
('215', 'Safety', 'Active Safety', 'Stability Control', 'Trailer Stability Assist', 2500, 60, 'Germany', 'Safety', 3.5, 'Trailer sway control.', 'STANDARD'),
('216', 'Safety', 'Active Safety', 'Stability Control', 'Full Stability Control', 4500, 72, 'USA', 'Safety', 4, 'ESC with yaw control.', 'PREMIUM'),
('217', 'Safety', 'Active Safety', 'Stability Control', 'Integrated Safety System', 8500, 95, 'USA', 'Safety', 5, 'ESC plus collision mitigation.', 'FLAGSHIP'),
('218', 'Safety', 'Passive Safety', 'Mirror System', 'Manual West Coast Mirrors', 0, 25, 'USA', 'Safety', 1, 'Basic manual adjust.', 'ENTRY'),
('219', 'Safety', 'Passive Safety', 'Mirror System', 'Convex Spot Mirrors', 250, 28, 'USA', 'Safety', 2, 'Additional convex mirrors.', 'STANDARD'),
('220', 'Safety', 'Passive Safety', 'Mirror System', 'Heated Power Mirrors', 650, 32, 'USA', 'Safety', 2.5, 'Electric adjust with heaters.', 'STANDARD'),
('221', 'Safety', 'Passive Safety', 'Mirror System', 'Power Fold Mirrors', 1200, 30, 'USA', 'Safety', 3.5, 'Electric fold with memory.', 'STANDARD'),
('222', 'Safety', 'Passive Safety', 'Mirror System', 'Aero Heated Mirrors', 1800, 28, 'USA', 'Safety', 4, 'Aerodynamic, reduced drag.', 'PREMIUM'),
('223', 'Safety', 'Passive Safety', 'Mirror System', 'Camera Mirror System', 5500, 18, 'USA', 'Safety', 5, 'Digital displays, no blind spots.', 'FLAGSHIP'),
('224', 'Transmission', 'Cooling', 'Transmission Cooler', 'Integrated Trans Cooler', 0, 15, 'USA', 'Cooling', 1, 'Basic in-radiator cooling.', 'ENTRY'),
('225', 'Transmission', 'Cooling', 'Transmission Cooler', 'External Trans Cooler', 650, 25, 'USA', 'Cooling', 2, 'Separate external cooler.', 'STANDARD'),
('226', 'Transmission', 'Cooling', 'Transmission Cooler', 'Auxiliary Trans Cooler', 950, 32, 'USA', 'Cooling', 2.5, 'Additional cooling capacity.', 'STANDARD'),
('227', 'Transmission', 'Cooling', 'Transmission Cooler', 'Stacked-Plate Cooler', 1200, 30, 'USA', 'Cooling', 3.5, 'Efficient stacked-plate design.', 'STANDARD'),
('228', 'Transmission', 'Cooling', 'Transmission Cooler', 'Heavy-Duty Trans Cooler', 1500, 38, 'USA', 'Cooling', 4, 'Large cooler with thermostat.', 'PREMIUM'),
('229', 'Transmission', 'Cooling', 'Transmission Cooler', 'Maximum Cooling Package', 3500, 55, 'USA', 'Cooling', 5, 'Oversized cooler with fan.', 'FLAGSHIP'),
('230', 'Transmission', 'PTO System', 'PTO Configuration', 'No PTO Provision', 0, 0, 'USA', 'Hauling', 1, 'Linehaul without PTO.', 'ENTRY'),
('231', 'Transmission', 'PTO System', 'PTO Configuration', 'Single PTO Opening', 450, 15, 'USA', 'Hauling', 2, 'Single-speed output.', 'STANDARD'),
('232', 'Transmission', 'PTO System', 'PTO Configuration', 'Dual PTO System', 1500, 35, 'USA', 'Hauling', 2.5, 'Front and rear PTO.', 'PREMIUM'),
('233', 'Transmission', 'PTO System', 'PTO Configuration', 'Live PTO System', 2200, 45, 'USA', 'Hauling', 3.5, 'Always-engaged PTO.', 'PREMIUM'),
('234', 'Transmission', 'PTO System', 'PTO Configuration', 'Hydraulic PTO Package', 2800, 55, 'USA', 'Hauling', 4, 'Full hydraulic PTO system.', 'PREMIUM'),
('235', 'Transmission', 'PTO System', 'PTO Configuration', 'Heavy-Duty PTO Package', 3500, 65, 'USA', 'Hauling', 5, 'Maximum PTO capacity.', 'FLAGSHIP'),
('236', 'Transmission', 'Transmission Assembly', 'Clutch System', 'Standard 14-inch Clutch', 0, 95, 'USA', 'Durability', 1, 'Basic 14-inch single plate.', 'ENTRY'),
('237', 'Transmission', 'Transmission Assembly', 'Clutch System', '14-inch Heavy-Duty Clutch', 450, 105, 'USA', 'Durability', 2, 'Enhanced 14-inch clutch.', 'STANDARD'),
('238', 'Transmission', 'Transmission Assembly', 'Clutch System', '15.5-inch Standard Clutch', 650, 115, 'USA', 'Durability', 2.5, 'Standard Class 8 clutch.', 'STANDARD'),
('239', 'Transmission', 'Transmission Assembly', 'Clutch System', '15.5-inch Heavy-Duty Clutch', 1800, 125, 'USA', 'Durability', 3.5, 'Higher torque rating.', 'PREMIUM'),
('240', 'Transmission', 'Transmission Assembly', 'Clutch System', 'Ceramic Heavy Clutch', 2500, 135, 'Germany', 'Durability', 4, 'Ceramic friction material.', 'PREMIUM'),
('241', 'Transmission', 'Transmission Assembly', 'Clutch System', 'Auto-Adjust Heavy Clutch', 3500, 145, 'USA', 'Durability', 5, 'Self-adjusting, extended life.', 'FLAGSHIP'),
('242', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Direct Drive Overdrive', 0, 0, 'USA', 'Economy', 1, 'Fuel economy focus.', 'ENTRY'),
('243', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Overdrive Transmission', 450, 0, 'USA', 'Economy', 2, 'Balance of economy and performance.', 'STANDARD'),
('244', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Economy Plus Ratios', 650, 0, 'USA', 'Economy', 2.5, 'Fuel-optimized gear spread.', 'STANDARD'),
('245', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Close-Ratio Performance', 850, 0, 'USA', 'Economy', 3.5, 'Close-ratio for performance.', 'STANDARD'),
('246', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Wide-Range Ratios', 1200, 0, 'USA', 'Economy', 4, 'Expanded ratio coverage.', 'PREMIUM'),
('247', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Deep-Reduction Heavy-Haul', 2500, 0, 'USA', 'Economy', 5, 'Maximum ratio spread.', 'FLAGSHIP'),
('248', 'Transmission', 'Transmission Assembly', 'Transmission Type', '10-Speed Manual', 0, 450, 'USA', 'Economy', 2, 'Basic 10-speed manual.', 'ENTRY'),
('249', 'Transmission', 'Transmission Assembly', 'Transmission Type', '9-Speed Economy', 200, 420, 'USA', 'Economy', 1, 'Entry 9-speed manual.', 'ENTRY'),
('250', 'Transmission', 'Transmission Assembly', 'Transmission Type', '13-Speed Manual', 1800, 485, 'USA', 'Economy', 2.5, 'Traditional 13-speed.', 'STANDARD'),
('251', 'Transmission', 'Transmission Assembly', 'Transmission Type', '10-Speed Automated', 3200, 495, 'USA', 'Economy', 3.5, '10-speed AMT option.', 'STANDARD'),
('252', 'Transmission', 'Transmission Assembly', 'Transmission Type', '12-Speed Automated Manual', 4500, 520, 'USA', 'Economy', 4, 'AMT with driver choice.', 'PREMIUM'),
('253', 'Transmission', 'Transmission Assembly', 'Transmission Type', '18-Speed Automatic', 8500, 580, 'Japan', 'Economy', 5, 'Full automatic with torque converter.', 'FLAGSHIP');

-- Verify count
SELECT 'BOM_TBL loaded: ' || COUNT(*) || ' rows' as status FROM BOM_TBL;
