-- Full BOM_TBL Data (253 rows) with SPECS included
-- Run after 02_data.sql

USE SCHEMA BOM.BOM4;

-- Clear existing sample data and insert full dataset
TRUNCATE TABLE IF EXISTS BOM_TBL;

INSERT INTO BOM_TBL (OPTION_ID, SYSTEM_NM, SUBSYSTEM_NM, COMPONENT_GROUP, OPTION_NM, COST_USD, WEIGHT_LBS, SOURCE_COUNTRY, PERFORMANCE_CATEGORY, PERFORMANCE_SCORE, DESCRIPTION, OPTION_TIER, SPECS)
SELECT * FROM (
    SELECT '1', 'Cab', 'Cab Structure', 'Cab Type', 'Day Cab Standard', 0.00, 1200.00, 'USA', 'Comfort', 1.0, 'Basic day cab for regional and local operations. No sleeping quarters.', 'ENTRY', PARSE_JSON('{"cab_class":"standard","cab_type":"day-cab","interior_height_in":58,"sleeper_length_in":0}') UNION ALL
    SELECT '2', 'Cab', 'Cab Structure', 'Cab Type', 'Low-Entry Day Cab', 1500.00, 1250.00, 'USA', 'Comfort', 1.5, 'Lower step-in height.', 'STANDARD', PARSE_JSON('{"cab_class":"low-entry","cab_type":"day-cab-low-entry","interior_height_in":54,"sleeper_length_in":0}') UNION ALL
    SELECT '3', 'Cab', 'Cab Structure', 'Cab Type', 'Day Cab Extended', 2500.00, 1350.00, 'USA', 'Comfort', 2.5, 'Extended day cab with additional storage and legroom.', 'STANDARD', PARSE_JSON('{"cab_class":"extended","cab_type":"day-cab-extended","interior_height_in":62,"sleeper_length_in":0}') UNION ALL
    SELECT '4', 'Cab', 'Cab Structure', 'Cab Type', 'Sleeper 48-inch Flat Roof', 6500.00, 1800.00, 'USA', 'Comfort', 3.0, 'Compact sleeper for budget-conscious fleets.', 'STANDARD', PARSE_JSON('{"cab_class":"compact-sleeper","cab_type":"sleeper","interior_height_in":65,"sleeper_length_in":48}') UNION ALL
    SELECT '5', 'Cab', 'Cab Structure', 'Cab Type', 'Crew Cab 4-Door', 8500.00, 1650.00, 'USA', 'Comfort', 3.5, 'Four-door crew cab for vocational.', 'STANDARD', PARSE_JSON('{"cab_class":"crew","cab_type":"crew-cab","doors":4,"interior_height_in":60,"sleeper_length_in":0}') UNION ALL
    SELECT '6', 'Cab', 'Cab Structure', 'Cab Type', 'Sleeper 72-inch Mid Roof', 12000.00, 2200.00, 'USA', 'Comfort', 4.5, 'Mid-roof sleeper with stand-up height.', 'PREMIUM', PARSE_JSON('{"cab_class":"mid-roof","cab_type":"sleeper","interior_height_in":76,"sleeper_length_in":72}') UNION ALL
    SELECT '7', 'Cab', 'Cab Structure', 'Cab Type', 'Sleeper 80-inch Raised Roof', 22000.00, 2600.00, 'USA', 'Comfort', 5.0, 'Full-height raised roof sleeper.', 'FLAGSHIP', PARSE_JSON('{"cab_class":"raised-roof","cab_type":"sleeper","interior_height_in":84,"sleeper_length_in":80}') UNION ALL
    SELECT '8', 'Cab', 'Climate Control', 'HVAC System', 'Manual Climate Control', 0.00, 45.00, 'Mexico', 'Comfort', 1.0, 'Basic manual HVAC with heater and A/C.', 'ENTRY', PARSE_JSON('{"cooling_btu":18000,"hvac_type":"manual","zones":1}') UNION ALL
    SELECT '9', 'Cab', 'Climate Control', 'HVAC System', 'Automatic Climate Control', 1200.00, 52.00, 'USA', 'Comfort', 2.0, 'Single-zone automatic temperature control.', 'STANDARD', PARSE_JSON('{"cooling_btu":22000,"hvac_type":"automatic","zones":1}') UNION ALL
    SELECT '10', 'Cab', 'Climate Control', 'HVAC System', 'High-Capacity A/C', 1800.00, 58.00, 'USA', 'Comfort', 2.5, 'Extra cooling capacity.', 'STANDARD', PARSE_JSON('{"cooling_btu":28000,"hvac_type":"automatic","zones":1}') UNION ALL
    SELECT '11', 'Cab', 'Climate Control', 'HVAC System', 'Dual-Zone Climate Control', 2800.00, 65.00, 'USA', 'Comfort', 3.5, 'Independent driver/passenger temperature zones.', 'PREMIUM', PARSE_JSON('{"cooling_btu":32000,"hvac_type":"automatic","zones":2}') UNION ALL
    SELECT '12', 'Cab', 'Climate Control', 'HVAC System', 'APU Climate System', 4200.00, 75.00, 'USA', 'Comfort', 4.0, 'Idle-free APU climate.', 'PREMIUM', PARSE_JSON('{"cooling_btu":28000,"hvac_type":"APU","idle_free":true,"zones":2}') UNION ALL
    SELECT '13', 'Cab', 'Climate Control', 'HVAC System', 'Tri-Zone Premium Climate', 5500.00, 85.00, 'USA', 'Comfort', 5.0, 'Three-zone control including sleeper.', 'FLAGSHIP', PARSE_JSON('{"cooling_btu":42000,"hvac_type":"automatic","zones":3}') UNION ALL
    SELECT '14', 'Cab', 'Interior', 'Interior Trim', 'Vinyl Work Trim', 0.00, 120.00, 'Mexico', 'Comfort', 1.0, 'Durable vinyl surfaces for work applications.', 'ENTRY', PARSE_JSON('{"durability":"work-grade","material":"vinyl","trim_level":1}') UNION ALL
    SELECT '15', 'Cab', 'Interior', 'Interior Trim', 'Heavy-Duty Vinyl Plus', 450.00, 125.00, 'Mexico', 'Comfort', 2.0, 'Enhanced work-grade vinyl.', 'STANDARD', PARSE_JSON('{"durability":"enhanced","material":"vinyl-plus","trim_level":2}') UNION ALL
    SELECT '16', 'Cab', 'Interior', 'Interior Trim', 'Cloth Standard Trim', 800.00, 135.00, 'USA', 'Comfort', 2.5, 'Standard cloth upholstery with vinyl accents.', 'STANDARD', PARSE_JSON('{"durability":"standard","material":"cloth","trim_level":2}') UNION ALL
    SELECT '17', 'Cab', 'Interior', 'Interior Trim', 'Premium Cloth Package', 2200.00, 150.00, 'USA', 'Comfort', 3.5, 'Upgraded cloth with leather steering wheel.', 'PREMIUM', PARSE_JSON('{"durability":"premium","material":"premium-cloth","trim_level":3}') UNION ALL
    SELECT '18', 'Cab', 'Interior', 'Interior Trim', 'Leather Sport Trim', 5500.00, 160.00, 'USA', 'Comfort', 4.0, 'Sporty leather with contrast stitching.', 'PREMIUM', PARSE_JSON('{"durability":"premium","material":"leather","trim_level":4}') UNION ALL
    SELECT '19', 'Cab', 'Interior', 'Interior Trim', 'Executive Leather Interior', 8500.00, 175.00, 'USA', 'Comfort', 5.0, 'Full leather surfaces with wood-grain accents.', 'FLAGSHIP', PARSE_JSON('{"durability":"luxury","material":"executive-leather","trim_level":5}') UNION ALL
    SELECT '20', 'Cab', 'Interior', 'Seating Configuration', 'Fixed Base Driver Seat', 0.00, 85.00, 'Mexico', 'Comfort', 1.0, 'Fixed position driver seat with basic adjustment.', 'ENTRY', PARSE_JSON('{"heating":false,"seat_type":"fixed-base","suspension":"none","ventilation":false}') UNION ALL
    SELECT '21', 'Cab', 'Interior', 'Seating Configuration', 'Air-Ride Driver Seat', 1500.00, 95.00, 'USA', 'Comfort', 2.0, 'Air-suspension seat with lumbar support.', 'STANDARD', PARSE_JSON('{"heating":false,"seat_type":"air-ride","suspension":"air","ventilation":false}') UNION ALL
    SELECT '22', 'Cab', 'Interior', 'Seating Configuration', 'Dual Air-Ride Team Seats', 2800.00, 190.00, 'USA', 'Comfort', 2.5, 'Matched team seating.', 'STANDARD', PARSE_JSON('{"heating":false,"seat_type":"dual-air-ride","suspension":"air","ventilation":false}') UNION ALL
    SELECT '23', 'Cab', 'Interior', 'Seating Configuration', 'Premium Air-Ride with Heat', 3200.00, 105.00, 'USA', 'Comfort', 3.5, 'Heated/ventilated air-ride seat.', 'PREMIUM', PARSE_JSON('{"heating":true,"seat_type":"premium-air-ride","suspension":"air","ventilation":true}') UNION ALL
    SELECT '24', 'Cab', 'Interior', 'Seating Configuration', 'Sport Bucket Seats', 4500.00, 115.00, 'Germany', 'Comfort', 4.0, 'Performance-oriented bucket seats.', 'PREMIUM', PARSE_JSON('{"heating":true,"seat_type":"sport-bucket","suspension":"mechanical","ventilation":false}') UNION ALL
    SELECT '25', 'Cab', 'Interior', 'Seating Configuration', 'Executive Massaging Seat', 6500.00, 125.00, 'USA', 'Comfort', 5.0, 'Full massage system, cooling/heating.', 'FLAGSHIP', PARSE_JSON('{"heating":true,"massage":true,"seat_type":"executive","suspension":"air","ventilation":true}') UNION ALL
    SELECT '26', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'No Sleeper (Day Cab)', 0.00, 0.00, 'USA', 'Comfort', 1.0, 'Day cab configuration - no sleeping quarters.', 'ENTRY', PARSE_JSON('{"bunk_type":"none","bunk_width_in":0,"mattress":"none"}') UNION ALL
    SELECT '27', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'Single Bunk 36-inch', 3500.00, 180.00, 'USA', 'Comfort', 2.0, 'Single bunk for solo drivers.', 'STANDARD', PARSE_JSON('{"bunk_type":"single","bunk_width_in":36,"mattress":"standard"}') UNION ALL
    SELECT '28', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'Double Bunk 42-inch', 6500.00, 280.00, 'USA', 'Comfort', 3.0, 'Team driver double bunk.', 'PREMIUM', PARSE_JSON('{"bunk_type":"double","bunk_width_in":42,"mattress":"standard"}') UNION ALL
    SELECT '29', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'King-Size Single 48-inch', 9500.00, 350.00, 'USA', 'Comfort', 4.0, 'Extra-wide single bunk with premium mattress.', 'FLAGSHIP', PARSE_JSON('{"bunk_type":"king-single","bunk_width_in":48,"mattress":"premium"}') UNION ALL
    SELECT '30', 'Cab', 'Sleeper Compartment', 'Bunk Configuration', 'Studio Sleeper 60-inch', 15000.00, 420.00, 'USA', 'Comfort', 5.0, 'Studio-style living space.', 'FLAGSHIP', PARSE_JSON('{"bunk_type":"studio","bunk_width_in":60,"mattress":"premium"}') UNION ALL
    SELECT '31', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'No Sleeper Amenities', 0.00, 0.00, 'USA', 'Comfort', 1.0, 'Day cab or basic sleeper - no amenities.', 'ENTRY', PARSE_JSON('{"amenity_level":0,"features":[]}') UNION ALL
    SELECT '32', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'Standard Sleeper Package', 2500.00, 85.00, 'USA', 'Comfort', 2.0, 'Overhead storage, reading lights, DC outlets.', 'STANDARD', PARSE_JSON('{"amenity_level":1,"features":["storage","lights","DC-outlets"]}') UNION ALL
    SELECT '33', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'Entertainment Package', 3500.00, 110.00, 'USA', 'Comfort', 3.0, 'TV, sound system, WiFi ready.', 'STANDARD', PARSE_JSON('{"amenity_level":2,"features":["TV","sound-system","WiFi"]}') UNION ALL
    SELECT '34', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'Premium Sleeper Package', 5500.00, 145.00, 'USA', 'Comfort', 4.0, 'Microwave, larger fridge, TV mount.', 'PREMIUM', PARSE_JSON('{"amenity_level":3,"features":["microwave","fridge","TV-mount"]}') UNION ALL
    SELECT '35', 'Cab', 'Sleeper Compartment', 'Sleeper Amenities', 'Luxury Living Package', 12000.00, 220.00, 'USA', 'Comfort', 5.0, 'Full kitchen, diesel generator, smart TV.', 'FLAGSHIP', PARSE_JSON('{"amenity_level":4,"features":["kitchen","generator","smart-TV"]}') UNION ALL
    SELECT '36', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Standard Fifth Wheel', 0.00, 210.00, 'USA', 'Hauling', 1.0, 'Standard for light-medium loads.', 'ENTRY', PARSE_JSON('{"fifth_wheel_class":"standard","gcwr_rating_lb":60000,"king_pin_size_in":2}') UNION ALL
    SELECT '37', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Low-Profile Fifth Wheel', 1500.00, 240.00, 'USA', 'Hauling', 1.5, 'Lower deck height option.', 'STANDARD', PARSE_JSON('{"fifth_wheel_class":"low-profile","gcwr_rating_lb":70000,"king_pin_size_in":2}') UNION ALL
    SELECT '38', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Sliding Fifth Wheel', 2200.00, 280.00, 'USA', 'Hauling', 2.5, 'Manual slide for weight distribution.', 'STANDARD', PARSE_JSON('{"fifth_wheel_class":"sliding","gcwr_rating_lb":80000,"king_pin_size_in":2}') UNION ALL
    SELECT '39', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Lightweight Aluminum Fifth', 3500.00, 180.00, 'USA', 'Hauling', 3.0, 'Weight-saving aluminum design.', 'STANDARD', PARSE_JSON('{"fifth_wheel_class":"lightweight","gcwr_rating_lb":75000,"king_pin_size_in":2}') UNION ALL
    SELECT '40', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Air-Slide Fifth Wheel', 4500.00, 320.00, 'USA', 'Hauling', 3.5, 'Air-powered sliding mechanism.', 'PREMIUM', PARSE_JSON('{"fifth_wheel_class":"air-slide","gcwr_rating_lb":85000,"king_pin_size_in":2.5}') UNION ALL
    SELECT '41', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Compensating Fifth Wheel', 5500.00, 350.00, 'USA', 'Hauling', 4.5, 'Self-aligning for uneven loads.', 'PREMIUM', PARSE_JSON('{"fifth_wheel_class":"compensating","gcwr_rating_lb":90000,"king_pin_size_in":2.5}') UNION ALL
    SELECT '42', 'Chassis', 'Fifth Wheel', 'Fifth Wheel Type', 'Heavy-Haul Fifth Wheel', 8500.00, 480.00, 'USA', 'Hauling', 5.0, 'Maximum GCWR capability.', 'FLAGSHIP', PARSE_JSON('{"fifth_wheel_class":"heavy-haul","gcwr_rating_lb":120000,"king_pin_size_in":3.5}') UNION ALL
    SELECT '43', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Standard Steel Frame', 0.00, 2800.00, 'USA', 'Durability', 1.0, 'Standard duty rating.', 'ENTRY', PARSE_JSON('{"frame_class":"standard","rbm_rating_in_lb":1800000,"yield_strength_psi":80000}') UNION ALL
    SELECT '44', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Reinforced Crossmembers', 2500.00, 3100.00, 'USA', 'Durability', 1.5, 'Extra crossmember bracing.', 'STANDARD', PARSE_JSON('{"frame_class":"reinforced","rbm_rating_in_lb":2200000,"yield_strength_psi":110000}') UNION ALL
    SELECT '45', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Heavy-Duty Steel Frame', 3500.00, 3200.00, 'USA', 'Durability', 2.5, 'Reinforced frame rails.', 'STANDARD', PARSE_JSON('{"frame_class":"heavy-duty","rbm_rating_in_lb":2800000,"yield_strength_psi":120000}') UNION ALL
    SELECT '46', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Corrosion-Resistant Frame', 5500.00, 3400.00, 'USA', 'Durability', 3.0, 'Galvanized frame rails.', 'PREMIUM', PARSE_JSON('{"frame_class":"corrosion-resistant","rbm_rating_in_lb":2400000,"yield_strength_psi":100000}') UNION ALL
    SELECT '47', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Extra Heavy-Duty Frame', 7500.00, 3800.00, 'USA', 'Durability', 3.5, 'Full-length reinforcement.', 'PREMIUM', PARSE_JSON('{"frame_class":"extra-heavy","rbm_rating_in_lb":3200000,"yield_strength_psi":120000}') UNION ALL
    SELECT '48', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Aluminum Hybrid Frame', 12000.00, 2400.00, 'USA', 'Durability', 4.5, 'Lightweight aluminum frame.', 'PREMIUM', PARSE_JSON('{"frame_class":"aluminum-hybrid","rbm_rating_in_lb":2000000,"yield_strength_psi":90000}') UNION ALL
    SELECT '49', 'Chassis', 'Frame Assembly', 'Frame Rails', 'Vocational Heavy-Haul Frame', 14000.00, 4500.00, 'USA', 'Durability', 5.0, 'Max RBM rating.', 'FLAGSHIP', PARSE_JSON('{"frame_class":"vocational","rbm_rating_in_lb":3800000,"yield_strength_psi":140000}') UNION ALL
    SELECT '50', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Ultra-Short 156-inch', 100.00, 0.00, 'USA', 'Hauling', 1.5, 'Minimum wheelbase for maneuverability.', 'ENTRY', PARSE_JSON('{"application":"urban","turning_radius_ft":22,"wheelbase_in":156}') UNION ALL
    SELECT '51', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Short Wheelbase 170-inch', 0.00, 0.00, 'USA', 'Hauling', 1.0, 'Urban maneuvering.', 'ENTRY', PARSE_JSON('{"application":"urban-regional","turning_radius_ft":25,"wheelbase_in":170}') UNION ALL
    SELECT '52', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Custom 195-inch', 400.00, 25.00, 'USA', 'Hauling', 2.5, 'Compact custom wheelbase.', 'STANDARD', PARSE_JSON('{"application":"custom","turning_radius_ft":28,"wheelbase_in":195}') UNION ALL
    SELECT '53', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Standard Wheelbase 210-inch', 800.00, 45.00, 'USA', 'Hauling', 3.0, 'General freight.', 'STANDARD', PARSE_JSON('{"application":"general-freight","turning_radius_ft":32,"wheelbase_in":210}') UNION ALL
    SELECT '54', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Mid-Length 228-inch', 1200.00, 65.00, 'USA', 'Hauling', 3.5, 'Versatile mid-length wheelbase.', 'STANDARD', PARSE_JSON('{"application":"versatile","turning_radius_ft":36,"wheelbase_in":228}') UNION ALL
    SELECT '55', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Extended Wheelbase 245-inch', 1800.00, 95.00, 'USA', 'Hauling', 4.5, 'Larger sleepers.', 'PREMIUM', PARSE_JSON('{"application":"sleeper","turning_radius_ft":40,"wheelbase_in":245}') UNION ALL
    SELECT '56', 'Chassis', 'Frame Assembly', 'Wheelbase', 'Long Wheelbase 280-inch', 3500.00, 150.00, 'USA', 'Hauling', 5.0, 'Heavy haul.', 'FLAGSHIP', PARSE_JSON('{"application":"heavy-haul","turning_radius_ft":48,"wheelbase_in":280}') UNION ALL
    SELECT '57', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Behind Cab 5-Gallon', 0.00, 25.00, 'USA', 'Emissions', 1.0, 'Compact DEF tank.', 'ENTRY', PARSE_JSON('{"def_capacity_gal":5,"def_location":"behind-cab","heated":false}') UNION ALL
    SELECT '58', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Frame-Mount 13-Gallon', 450.00, 35.00, 'USA', 'Emissions', 2.0, 'Standard frame-mounted.', 'STANDARD', PARSE_JSON('{"def_capacity_gal":13,"def_location":"frame-mount","heated":true}') UNION ALL
    SELECT '59', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Integrated DEF 10-Gallon', 650.00, 30.00, 'USA', 'Emissions', 2.5, 'Frame-integrated DEF tank.', 'STANDARD', PARSE_JSON('{"def_capacity_gal":10,"def_location":"integrated","heated":true}') UNION ALL
    SELECT '60', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Under-Cab 15-Gallon', 750.00, 40.00, 'USA', 'Emissions', 3.5, 'Space-saving under-cab mount.', 'STANDARD', PARSE_JSON('{"def_capacity_gal":15,"def_location":"under-cab","heated":true}') UNION ALL
    SELECT '61', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Saddle-Mount 18-Gallon', 950.00, 48.00, 'USA', 'Emissions', 4.0, 'Large capacity heated.', 'PREMIUM', PARSE_JSON('{"def_capacity_gal":18,"def_location":"saddle-mount","heated":true}') UNION ALL
    SELECT '62', 'Chassis', 'Fuel System', 'DEF Tank Location', 'Dual Tank 26-Gallon', 1800.00, 72.00, 'USA', 'Emissions', 5.0, 'Maximum DEF capacity.', 'FLAGSHIP', PARSE_JSON('{"def_capacity_gal":26,"def_location":"dual-tank","heated":true}') UNION ALL
    SELECT '63', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Single 100-Gallon Aluminum', 0.00, 85.00, 'USA', 'Economy', 1.0, '600-mile range.', 'ENTRY', PARSE_JSON('{"range_miles":600,"tank_capacity_gal":100,"tank_count":1,"tank_material":"aluminum"}') UNION ALL
    SELECT '64', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Single 125-Gallon Steel', 800.00, 145.00, 'USA', 'Economy', 1.5, 'Steel tank option.', 'STANDARD', PARSE_JSON('{"range_miles":750,"tank_capacity_gal":125,"tank_count":1,"tank_material":"steel"}') UNION ALL
    SELECT '65', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Dual 100-Gallon Aluminum', 1800.00, 170.00, 'USA', 'Economy', 2.5, '1200-mile range.', 'STANDARD', PARSE_JSON('{"range_miles":1200,"tank_capacity_gal":200,"tank_count":2,"tank_material":"aluminum"}') UNION ALL
    SELECT '66', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Single 150-Gallon Aluminum', 2200.00, 128.00, 'USA', 'Economy', 3.0, '900-mile range single tank.', 'STANDARD', PARSE_JSON('{"range_miles":900,"tank_capacity_gal":150,"tank_count":1,"tank_material":"aluminum"}') UNION ALL
    SELECT '67', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Dual 150-Gallon Aluminum', 3200.00, 255.00, 'USA', 'Economy', 3.5, '1800-mile range.', 'PREMIUM', PARSE_JSON('{"range_miles":1800,"tank_capacity_gal":300,"tank_count":2,"tank_material":"aluminum"}') UNION ALL
    SELECT '68', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Dual 200-Gallon Aluminum', 5500.00, 340.00, 'USA', 'Economy', 4.5, '2400-mile range.', 'FLAGSHIP', PARSE_JSON('{"range_miles":2400,"tank_capacity_gal":400,"tank_count":2,"tank_material":"aluminum"}') UNION ALL
    SELECT '69', 'Chassis', 'Fuel System', 'Fuel Tank Configuration', 'Tri-Tank 225-Gallon', 7500.00, 395.00, 'USA', 'Economy', 5.0, 'Three-tank maximum range.', 'FLAGSHIP', PARSE_JSON('{"range_miles":1350,"tank_capacity_gal":225,"tank_count":3,"tank_material":"aluminum"}') UNION ALL
    SELECT '70', 'Electrical', 'Electronics', 'ADAS Features', 'Basic Safety Suite', 0.00, 15.00, 'Japan', 'Safety', 1.0, 'Basic ABS and stability control.', 'ENTRY', PARSE_JSON('{"adas_level":0,"features":["ABS","stability-control"],"sensors":["wheel-speed"]}') UNION ALL
    SELECT '71', 'Electrical', 'Electronics', 'ADAS Features', 'Rear Cross-Traffic Alert', 2200.00, 20.00, 'Japan', 'Safety', 2.0, 'Backing collision prevention.', 'STANDARD', PARSE_JSON('{"adas_level":1,"features":["rear-cross-traffic"],"sensors":["rear-radar"]}') UNION ALL
    SELECT '72', 'Electrical', 'Electronics', 'ADAS Features', 'Standard ADAS Package', 3500.00, 28.00, 'USA', 'Safety', 2.5, 'Forward collision warning, lane departure.', 'STANDARD', PARSE_JSON('{"adas_level":1,"features":["FCW","LDW"],"sensors":["front-camera","front-radar"]}') UNION ALL
    SELECT '73', 'Electrical', 'Electronics', 'ADAS Features', 'Commercial ADAS Plus', 5500.00, 35.00, 'USA', 'Safety', 3.5, 'Mid-tier safety package.', 'STANDARD', PARSE_JSON('{"adas_level":2,"features":["FCW","LDW","AEB"],"sensors":["front-camera","front-radar","side-radar"]}') UNION ALL
    SELECT '74', 'Electrical', 'Electronics', 'ADAS Features', 'Advanced ADAS Package', 7500.00, 42.00, 'USA', 'Safety', 4.0, 'Auto emergency braking, adaptive cruise.', 'PREMIUM', PARSE_JSON('{"adas_level":2,"features":["AEB","ACC","LKA"],"sensors":["front-camera","front-radar","lidar"]}') UNION ALL
    SELECT '75', 'Electrical', 'Electronics', 'ADAS Features', 'Full ADAS Highway Pilot', 15000.00, 65.00, 'USA', 'Safety', 5.0, 'Level 2 highway pilot, 360-degree sensors.', 'FLAGSHIP', PARSE_JSON('{"adas_level":2,"features":["highway-pilot","360-view"],"sensors":["front-camera","rear-camera","surround-radar","lidar"]}') UNION ALL
    SELECT '76', 'Electrical', 'Electronics', 'Telematics', 'Basic GPS Tracking', 0.00, 2.00, 'China', 'Economy', 1.0, 'Simple GPS location tracking.', 'ENTRY', PARSE_JSON('{"eld_compliant":false,"features":["GPS"],"telematics_level":1}') UNION ALL
    SELECT '77', 'Electrical', 'Electronics', 'Telematics', 'Fleet Telematics Standard', 1500.00, 5.00, 'USA', 'Economy', 2.0, 'GPS, ELD compliance, fuel tracking.', 'STANDARD', PARSE_JSON('{"eld_compliant":true,"features":["GPS","ELD","fuel-tracking"],"telematics_level":2}') UNION ALL
    SELECT '78', 'Electrical', 'Electronics', 'Telematics', 'Fuel Coach System', 2000.00, 4.00, 'USA', 'Economy', 2.5, 'Real-time fuel coaching.', 'STANDARD', PARSE_JSON('{"eld_compliant":true,"features":["fuel-coaching","driver-score"],"telematics_level":2}') UNION ALL
    SELECT '79', 'Electrical', 'Electronics', 'Telematics', 'Video Telematics', 2500.00, 6.00, 'USA', 'Economy', 3.5, 'Dash cam integration.', 'STANDARD', PARSE_JSON('{"eld_compliant":true,"features":["dash-cam","event-recording"],"telematics_level":3}') UNION ALL
    SELECT '80', 'Electrical', 'Electronics', 'Telematics', 'Advanced Fleet Management', 3500.00, 8.00, 'USA', 'Economy', 4.0, 'Real-time diagnostics, predictive maintenance.', 'PREMIUM', PARSE_JSON('{"eld_compliant":true,"features":["diagnostics","predictive-maintenance","real-time"],"telematics_level":4}') UNION ALL
    SELECT '81', 'Electrical', 'Electronics', 'Telematics', 'Enterprise Telematics Suite', 6500.00, 12.00, 'USA', 'Economy', 5.0, 'Full fleet intelligence, route optimization.', 'FLAGSHIP', PARSE_JSON('{"eld_compliant":true,"features":["fleet-intelligence","route-optimization","AI-analytics"],"telematics_level":5}') UNION ALL
    SELECT '82', 'Electrical', 'Lighting', 'Headlights', 'Halogen Headlights', 0.00, 8.00, 'Mexico', 'Safety', 1.0, 'Standard halogen sealed beam.', 'ENTRY', PARSE_JSON('{"light_class":"standard","light_type":"halogen","lumens":1200}') UNION ALL
    SELECT '83', 'Electrical', 'Lighting', 'Headlights', 'Fog Light Package', 450.00, 5.00, 'USA', 'Safety', 2.0, 'Auxiliary fog lights.', 'STANDARD', PARSE_JSON('{"light_class":"fog-package","light_type":"halogen-fog","lumens":1500}') UNION ALL
    SELECT '84', 'Electrical', 'Lighting', 'Headlights', 'Projector Halogen Lights', 650.00, 12.00, 'USA', 'Safety', 2.5, 'Projector-style with improved focus.', 'STANDARD', PARSE_JSON('{"light_class":"projector","light_type":"projector-halogen","lumens":1800}') UNION ALL
    SELECT '85', 'Electrical', 'Lighting', 'Headlights', 'Bi-LED Projector System', 1500.00, 9.00, 'Japan', 'Safety', 3.5, 'Mid-range LED system.', 'STANDARD', PARSE_JSON('{"light_class":"mid-LED","light_type":"bi-LED","lumens":3000}') UNION ALL
    SELECT '86', 'Electrical', 'Lighting', 'Headlights', 'LED Headlight System', 2200.00, 6.00, 'USA', 'Safety', 4.0, 'Full LED headlights and markers.', 'PREMIUM', PARSE_JSON('{"light_class":"LED","light_type":"full-LED","lumens":4500}') UNION ALL
    SELECT '87', 'Electrical', 'Lighting', 'Headlights', 'Adaptive LED Matrix Lights', 4500.00, 9.00, 'USA', 'Safety', 5.0, 'Matrix LED with auto high beam.', 'FLAGSHIP', PARSE_JSON('{"auto_high_beam":true,"light_class":"adaptive","light_type":"matrix-LED","lumens":6000}') UNION ALL
    SELECT '88', 'Electrical', 'Power Generation', 'Alternator', '160 Amp Alternator', 0.00, 28.00, 'Mexico', 'Power', 1.0, 'Standard 160A for basic loads.', 'ENTRY', PARSE_JSON('{"electrical_class":"standard","output_amps":160}') UNION ALL
    SELECT '89', 'Electrical', 'Power Generation', 'Alternator', '200 Amp High-Efficiency', 650.00, 32.00, 'USA', 'Power', 2.0, 'Efficient mid-range alternator.', 'STANDARD', PARSE_JSON('{"electrical_class":"high-efficiency","output_amps":200}') UNION ALL
    SELECT '90', 'Electrical', 'Power Generation', 'Alternator', '250 Amp Alternator', 850.00, 35.00, 'USA', 'Power', 2.5, 'High-output for accessories.', 'STANDARD', PARSE_JSON('{"electrical_class":"high-output","output_amps":250}') UNION ALL
    SELECT '91', 'Electrical', 'Power Generation', 'Alternator', '280 Amp Brushless', 1500.00, 40.00, 'USA', 'Power', 3.5, 'Brushless high-output.', 'STANDARD', PARSE_JSON('{"electrical_class":"brushless","output_amps":280}') UNION ALL
    SELECT '92', 'Electrical', 'Power Generation', 'Alternator', '320 Amp Dual Alternator', 2200.00, 65.00, 'USA', 'Power', 4.0, 'Dual alternator for heavy demands.', 'PREMIUM', PARSE_JSON('{"electrical_class":"dual","output_amps":320}') UNION ALL
    SELECT '93', 'Electrical', 'Power Generation', 'Alternator', '400 Amp Triple Alternator', 4500.00, 95.00, 'USA', 'Power', 5.0, 'Maximum electrical capacity.', 'FLAGSHIP', PARSE_JSON('{"electrical_class":"triple","output_amps":400}') UNION ALL
    SELECT '94', 'Electrical', 'Power Generation', 'Battery System', 'Dual 12V Standard Batteries', 0.00, 130.00, 'USA', 'Power', 1.0, 'Standard dual Group 31, 1900 CCA.', 'ENTRY', PARSE_JSON('{"battery_count":2,"battery_type":"lead-acid","cca_rating":1900}') UNION ALL
    SELECT '95', 'Electrical', 'Power Generation', 'Battery System', 'Triple 12V Heavy-Duty', 450.00, 195.00, 'USA', 'Power', 2.0, 'Three Group 31, 2850 CCA.', 'STANDARD', PARSE_JSON('{"battery_count":3,"battery_type":"lead-acid","cca_rating":2850}') UNION ALL
    SELECT '96', 'Electrical', 'Power Generation', 'Battery System', 'Cold-Weather Battery Pack', 650.00, 210.00, 'USA', 'Power', 2.5, 'High-CCA cold weather.', 'STANDARD', PARSE_JSON('{"battery_count":2,"battery_type":"cold-weather","cca_rating":2400}') UNION ALL
    SELECT '97', 'Electrical', 'Power Generation', 'Battery System', 'Dual AGM Premium', 850.00, 150.00, 'USA', 'Power', 3.5, 'Premium AGM dual batteries.', 'STANDARD', PARSE_JSON('{"battery_count":2,"battery_type":"AGM","cca_rating":2200}') UNION ALL
    SELECT '98', 'Electrical', 'Power Generation', 'Battery System', 'Quad AGM Battery System', 1200.00, 240.00, 'USA', 'Power', 4.0, 'Four AGM batteries with isolator.', 'PREMIUM', PARSE_JSON('{"battery_count":4,"battery_type":"AGM","cca_rating":4000}') UNION ALL
    SELECT '99', 'Electrical', 'Power Generation', 'Battery System', 'Lithium-Ion Auxiliary', 3500.00, 85.00, 'USA', 'Power', 5.0, 'Lithium auxiliary bank, 10-year life.', 'FLAGSHIP', PARSE_JSON('{"auxiliary":true,"battery_count":1,"battery_type":"lithium-ion","cca_rating":0}') UNION ALL
    SELECT '100', 'Engine', 'Cooling System', 'Fan Assembly', 'Belt-Drive Fixed Fan', 0.00, 45.00, 'USA', 'Cooling', 1.0, 'Simple belt-driven fan.', 'ENTRY', PARSE_JSON('{"cfm_rating":4500,"fan_type":"belt-drive-fixed","max_cooling_btu":220000}') UNION ALL
    SELECT '101', 'Engine', 'Cooling System', 'Fan Assembly', 'High-CFM Fixed Fan', 350.00, 50.00, 'USA', 'Cooling', 2.0, 'High-airflow fixed fan.', 'STANDARD', PARSE_JSON('{"cfm_rating":5500,"fan_type":"high-cfm-fixed","max_cooling_btu":280000}') UNION ALL
    SELECT '102', 'Engine', 'Cooling System', 'Fan Assembly', 'Viscous Clutch Fan', 650.00, 58.00, 'USA', 'Cooling', 2.5, 'Temperature-controlled viscous clutch.', 'STANDARD', PARSE_JSON('{"cfm_rating":6000,"fan_type":"viscous-clutch","max_cooling_btu":320000}') UNION ALL
    SELECT '103', 'Engine', 'Cooling System', 'Fan Assembly', 'Electric Fan with Clutch', 1800.00, 72.00, 'USA', 'Cooling', 3.5, 'Electronically-controlled fan.', 'PREMIUM', PARSE_JSON('{"cfm_rating":6500,"fan_type":"electric-clutch","max_cooling_btu":380000}') UNION ALL
    SELECT '104', 'Engine', 'Cooling System', 'Fan Assembly', 'Dual Electric Fans', 2500.00, 65.00, 'USA', 'Cooling', 4.0, 'Redundant dual fan system.', 'PREMIUM', PARSE_JSON('{"cfm_rating":7500,"fan_type":"dual-electric","max_cooling_btu":450000}') UNION ALL
    SELECT '105', 'Engine', 'Cooling System', 'Fan Assembly', 'Variable-Speed Electric Fan', 3500.00, 85.00, 'USA', 'Cooling', 5.0, 'Infinitely variable fan speed.', 'FLAGSHIP', PARSE_JSON('{"cfm_rating":8500,"fan_type":"variable-speed","max_cooling_btu":500000}') UNION ALL
    SELECT '106', 'Engine', 'Cooling System', 'Radiator', 'Standard Aluminum Radiator', 0.00, 95.00, 'USA', 'Cooling', 1.0, 'Standard capacity.', 'ENTRY', PARSE_JSON('{"cooling_capacity_btu":220000,"core_rows":3,"radiator_class":"standard"}') UNION ALL
    SELECT '107', 'Engine', 'Cooling System', 'Radiator', 'High-Capacity Radiator', 1200.00, 115.00, 'China', 'Cooling', 2.0, '20% increased capacity.', 'STANDARD', PARSE_JSON('{"cooling_capacity_btu":265000,"core_rows":4,"radiator_class":"high-capacity"}') UNION ALL
    SELECT '108', 'Engine', 'Cooling System', 'Radiator', 'Aluminum-Brass Radiator', 1800.00, 125.00, 'China', 'Cooling', 2.5, 'Hybrid aluminum-brass design.', 'STANDARD', PARSE_JSON('{"cooling_capacity_btu":280000,"core_rows":4,"radiator_class":"hybrid"}') UNION ALL
    SELECT '109', 'Engine', 'Cooling System', 'Radiator', 'Extended Core Radiator', 2000.00, 130.00, 'China', 'Cooling', 3.5, 'Extended core for moderate duty.', 'STANDARD', PARSE_JSON('{"cooling_capacity_btu":320000,"core_rows":5,"radiator_class":"extended-core"}') UNION ALL
    SELECT '110', 'Engine', 'Cooling System', 'Radiator', 'Heavy-Duty Cooling Package', 2800.00, 145.00, 'China', 'Cooling', 4.0, 'Oversized with auxiliary cooler.', 'PREMIUM', PARSE_JSON('{"cooling_capacity_btu":400000,"core_rows":6,"radiator_class":"heavy-duty"}') UNION ALL
    SELECT '111', 'Engine', 'Cooling System', 'Radiator', 'Extreme Duty Cooling', 5500.00, 185.00, 'China', 'Cooling', 5.0, 'Maximum cooling capacity.', 'FLAGSHIP', PARSE_JSON('{"cooling_capacity_btu":500000,"core_rows":7,"radiator_class":"extreme-duty"}') UNION ALL
    SELECT '112', 'Engine', 'Emissions System', 'DEF System', 'Standard SCR System', 0.00, 145.00, 'USA', 'Emissions', 1.0, 'Basic SCR, EPA 2017 compliant.', 'ENTRY', PARSE_JSON('{"def_consumption_pct":3,"emissions_standard":"EPA-2017","nox_reduction_pct":90}') UNION ALL
    SELECT '113', 'Engine', 'Emissions System', 'DEF System', 'Enhanced SCR System', 1500.00, 165.00, 'USA', 'Emissions', 2.0, 'Improved DEF dosing.', 'STANDARD', PARSE_JSON('{"def_consumption_pct":2.5,"emissions_standard":"EPA-2021","nox_reduction_pct":94}') UNION ALL
    SELECT '114', 'Engine', 'Emissions System', 'DEF System', 'Low-Consumption SCR', 2500.00, 175.00, 'USA', 'Emissions', 2.5, 'Reduced DEF consumption.', 'STANDARD', PARSE_JSON('{"def_consumption_pct":2,"emissions_standard":"EPA-2021","nox_reduction_pct":92}') UNION ALL
    SELECT '115', 'Engine', 'Emissions System', 'DEF System', 'Advanced Emissions Package', 3500.00, 195.00, 'USA', 'Emissions', 3.5, 'Integrated DPF/SCR, near-zero NOx.', 'PREMIUM', PARSE_JSON('{"def_consumption_pct":2.2,"emissions_standard":"EPA-2024","nox_reduction_pct":97}') UNION ALL
    SELECT '116', 'Engine', 'Emissions System', 'DEF System', 'Premium Emissions Control', 4500.00, 210.00, 'Germany', 'Emissions', 4.0, 'Premium emission system.', 'PREMIUM', PARSE_JSON('{"def_consumption_pct":2.8,"emissions_standard":"EPA-2024","nox_reduction_pct":96}') UNION ALL
    SELECT '117', 'Engine', 'Emissions System', 'DEF System', 'Ultra-Clean Emissions', 6500.00, 225.00, 'USA', 'Emissions', 5.0, 'CARB compliant, low-emission zone ready.', 'FLAGSHIP', PARSE_JSON('{"def_consumption_pct":3.2,"emissions_standard":"CARB","low_emission_zone_ready":true,"nox_reduction_pct":99}') UNION ALL
    SELECT '118', 'Engine', 'Engine Block', 'Engine Displacement', '6.7L Medium-Duty Diesel', 0.00, 1100.00, 'USA', 'Power', 1.0, 'Compact diesel, best fuel economy.', 'ENTRY', PARSE_JSON('{"displacement_liters":6.7,"engine_weight_lb":1150,"max_hp_supported":300,"max_torque_supported":900}') UNION ALL
    SELECT '119', 'Engine', 'Engine Block', 'Engine Displacement', '7.2L Regional Diesel', 1500.00, 1050.00, 'USA', 'Power', 1.5, 'Optimized for regional routes.', 'STANDARD', PARSE_JSON('{"displacement_liters":7.2,"engine_weight_lb":1280,"max_hp_supported":350,"max_torque_supported":1100}') UNION ALL
    SELECT '120', 'Engine', 'Engine Block', 'Engine Displacement', '9L Mid-Range Diesel', 4500.00, 1250.00, 'USA', 'Power', 2.0, 'Balance of power and efficiency.', 'STANDARD', PARSE_JSON('{"displacement_liters":9,"engine_weight_lb":1650,"max_hp_supported":400,"max_torque_supported":1400}') UNION ALL
    SELECT '121', 'Engine', 'Engine Block', 'Engine Displacement', '10L Balanced Diesel', 5500.00, 1300.00, 'USA', 'Power', 2.5, 'Mid-size balanced engine.', 'STANDARD', PARSE_JSON('{"displacement_liters":10,"engine_weight_lb":1850,"max_hp_supported":430,"max_torque_supported":1550}') UNION ALL
    SELECT '122', 'Engine', 'Engine Block', 'Engine Displacement', '11L Mid-Plus Diesel', 6500.00, 1350.00, 'USA', 'Power', 3.5, 'Versatile mid-range power.', 'PREMIUM', PARSE_JSON('{"displacement_liters":11,"engine_weight_lb":2100,"max_hp_supported":480,"max_torque_supported":1700}') UNION ALL
    SELECT '123', 'Engine', 'Engine Block', 'Engine Displacement', '13L Class 8 Diesel', 9500.00, 1450.00, 'USA', 'Power', 4.0, 'Industry-standard Class 8 engine.', 'PREMIUM', PARSE_JSON('{"displacement_liters":13,"engine_weight_lb":2450,"max_hp_supported":550,"max_torque_supported":1850}') UNION ALL
    SELECT '124', 'Engine', 'Engine Block', 'Engine Displacement', '15L Heavy-Haul Diesel', 16000.00, 1650.00, 'USA', 'Power', 4.5, 'Maximum displacement.', 'FLAGSHIP', PARSE_JSON('{"displacement_liters":15,"engine_weight_lb":2850,"max_hp_supported":600,"max_torque_supported":2000}') UNION ALL
    SELECT '125', 'Engine', 'Engine Block', 'Engine Displacement', '16L Maximum Diesel', 22000.00, 1800.00, 'USA', 'Power', 5.0, 'Largest available displacement.', 'FLAGSHIP', PARSE_JSON('{"displacement_liters":16,"engine_weight_lb":3100,"max_hp_supported":650,"max_torque_supported":2200}') UNION ALL
    SELECT '126', 'Engine', 'Engine Block', 'Power Rating', '260 HP / 660 lb-ft', 0.00, 0.00, 'USA', 'Power', 1.0, 'Entry-level power for light loads.', 'ENTRY', PARSE_JSON('{"cooling_requirement_btu":180000,"horsepower":260,"power_class":"entry","torque_lb_ft":660}') UNION ALL
    SELECT '127', 'Engine', 'Engine Block', 'Power Rating', '300 HP / 860 lb-ft Regional', 1200.00, 5.00, 'USA', 'Power', 1.5, 'Regional delivery power.', 'STANDARD', PARSE_JSON('{"cooling_requirement_btu":210000,"horsepower":300,"power_class":"regional","torque_lb_ft":860}') UNION ALL
    SELECT '128', 'Engine', 'Engine Block', 'Power Rating', '350 HP / 1150 lb-ft', 2500.00, 15.00, 'USA', 'Power', 2.0, 'Standard power for general freight.', 'STANDARD', PARSE_JSON('{"cooling_requirement_btu":250000,"horsepower":350,"power_class":"standard","torque_lb_ft":1150}') UNION ALL
    SELECT '129', 'Engine', 'Engine Block', 'Power Rating', '380 HP / 1250 lb-ft Fleet', 3500.00, 18.00, 'USA', 'Power', 2.5, 'Fleet-optimized power.', 'STANDARD', PARSE_JSON('{"cooling_requirement_btu":270000,"horsepower":380,"power_class":"fleet","torque_lb_ft":1250}') UNION ALL
    SELECT '130', 'Engine', 'Engine Block', 'Power Rating', '400 HP / 1400 lb-ft Mid-Range', 4500.00, 20.00, 'USA', 'Power', 3.0, 'Fleet workhorse power.', 'PREMIUM', PARSE_JSON('{"cooling_requirement_btu":290000,"horsepower":400,"power_class":"mid-range","torque_lb_ft":1400}') UNION ALL
    SELECT '131', 'Engine', 'Engine Block', 'Power Rating', '450 HP / 1650 lb-ft', 6500.00, 25.00, 'USA', 'Power', 3.5, 'High-output for heavy loads.', 'PREMIUM', PARSE_JSON('{"cooling_requirement_btu":330000,"horsepower":450,"power_class":"high-output","torque_lb_ft":1650}') UNION ALL
    SELECT '132', 'Engine', 'Engine Block', 'Power Rating', '500 HP / 1750 lb-ft Heavy', 8500.00, 32.00, 'USA', 'Power', 4.0, 'Heavy-duty power rating.', 'PREMIUM', PARSE_JSON('{"cooling_requirement_btu":370000,"horsepower":500,"power_class":"heavy-duty","torque_lb_ft":1750}') UNION ALL
    SELECT '133', 'Engine', 'Engine Block', 'Power Rating', '565 HP / 1850 lb-ft', 12000.00, 40.00, 'USA', 'Power', 4.5, 'Maximum power for heavy haul.', 'FLAGSHIP', PARSE_JSON('{"cooling_requirement_btu":420000,"horsepower":565,"power_class":"maximum","torque_lb_ft":1850}') UNION ALL
    SELECT '134', 'Engine', 'Engine Block', 'Power Rating', '605 HP / 2050 lb-ft Maximum', 18000.00, 55.00, 'USA', 'Power', 5.0, 'Ultimate heavy haul power.', 'FLAGSHIP', PARSE_JSON('{"cooling_requirement_btu":450000,"horsepower":605,"power_class":"ultimate","torque_lb_ft":2050}') UNION ALL
    SELECT '135', 'Engine', 'Engine Block', 'Turbocharger', 'Single Fixed-Geometry Turbo', 0.00, 45.00, 'Japan', 'Power', 1.0, 'Simple fixed turbo.', 'ENTRY', PARSE_JSON('{"boost_psi":18,"max_hp_supported":350,"turbo_type":"fixed-geometry"}') UNION ALL
    SELECT '136', 'Engine', 'Engine Block', 'Turbocharger', 'Variable Geometry Turbo', 2200.00, 52.00, 'USA', 'Power', 2.0, 'VGT, reduced turbo lag.', 'STANDARD', PARSE_JSON('{"boost_psi":28,"max_hp_supported":450,"turbo_type":"variable-geometry"}') UNION ALL
    SELECT '137', 'Engine', 'Engine Block', 'Turbocharger', 'Twin-Scroll VGT', 4500.00, 68.00, 'USA', 'Power', 2.5, 'Better low-end torque.', 'PREMIUM', PARSE_JSON('{"boost_psi":32,"max_hp_supported":500,"turbo_type":"twin-scroll-vgt"}') UNION ALL
    SELECT '138', 'Engine', 'Engine Block', 'Turbocharger', 'Electric Assist Turbo', 6500.00, 58.00, 'Germany', 'Power', 3.5, 'E-turbo for instant response.', 'PREMIUM', PARSE_JSON('{"boost_psi":35,"max_hp_supported":550,"turbo_type":"electric-assist"}') UNION ALL
    SELECT '139', 'Engine', 'Engine Block', 'Turbocharger', 'Compound Turbo System', 8500.00, 95.00, 'USA', 'Power', 4.0, 'Series turbos, max boost.', 'FLAGSHIP', PARSE_JSON('{"boost_psi":42,"max_hp_supported":600,"turbo_type":"compound"}') UNION ALL
    SELECT '140', 'Engine', 'Engine Block', 'Turbocharger', 'Twin VGT System', 12000.00, 85.00, 'Germany', 'Power', 5.0, 'Dual variable geometry turbos.', 'FLAGSHIP', PARSE_JSON('{"boost_psi":48,"max_hp_supported":650,"turbo_type":"twin-vgt"}') UNION ALL
    SELECT '141', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Exhaust Brake Only', 0.00, 25.00, 'USA', 'Safety', 1.0, 'Basic exhaust brake.', 'ENTRY', PARSE_JSON('{"brake_stages":1,"brake_type":"exhaust","braking_hp":100}') UNION ALL
    SELECT '142', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Engine Compression Brake', 2500.00, 45.00, 'USA', 'Safety', 2.0, 'Jake brake system.', 'STANDARD', PARSE_JSON('{"brake_stages":1,"brake_type":"compression","braking_hp":300}') UNION ALL
    SELECT '143', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Two-Stage Engine Brake', 3500.00, 55.00, 'USA', 'Safety', 2.5, 'Variable two-stage jake.', 'STANDARD', PARSE_JSON('{"brake_stages":2,"brake_type":"compression","braking_hp":400}') UNION ALL
    SELECT '144', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Integrated Retarder System', 5500.00, 85.00, 'USA', 'Safety', 3.5, 'Engine brake plus driveline retarder.', 'PREMIUM', PARSE_JSON('{"brake_stages":2,"brake_type":"integrated-retarder","braking_hp":500}') UNION ALL
    SELECT '145', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Three-Stage Engine Brake', 6500.00, 75.00, 'USA', 'Safety', 4.0, 'Three-level braking.', 'PREMIUM', PARSE_JSON('{"brake_stages":3,"brake_type":"compression","braking_hp":550}') UNION ALL
    SELECT '146', 'Engine', 'Engine Brake', 'Engine Brake Type', 'Full Retarder Package', 9500.00, 125.00, 'USA', 'Safety', 5.0, 'Maximum braking.', 'FLAGSHIP', PARSE_JSON('{"brake_stages":3,"brake_type":"full-retarder","braking_hp":650}') UNION ALL
    SELECT '147', 'Front Axle', 'Axle Assembly', 'Axle Rating', '12,000 lb Front Axle', 0.00, 550.00, 'USA', 'Hauling', 1.0, 'Light-duty front axle.', 'ENTRY', PARSE_JSON('{"axle_class":"light","beam_thickness_in":3.5,"gawr_lb":12000,"kingpin_size_in":2}') UNION ALL
    SELECT '148', 'Front Axle', 'Axle Assembly', 'Axle Rating', '13,200 lb Front Axle', 650.00, 580.00, 'USA', 'Hauling', 1.5, 'Light-medium front axle.', 'STANDARD', PARSE_JSON('{"axle_class":"light-medium","beam_thickness_in":3.5,"gawr_lb":13200,"kingpin_size_in":2}') UNION ALL
    SELECT '149', 'Front Axle', 'Axle Assembly', 'Axle Rating', '14,600 lb Front Axle', 1200.00, 620.00, 'USA', 'Hauling', 2.5, 'Standard Class 8 front axle.', 'STANDARD', PARSE_JSON('{"axle_class":"standard","beam_thickness_in":4,"gawr_lb":14600,"kingpin_size_in":2.25}') UNION ALL
    SELECT '150', 'Front Axle', 'Axle Assembly', 'Axle Rating', '16,000 lb Front Axle', 2000.00, 680.00, 'USA', 'Hauling', 3.0, 'Medium-heavy front axle.', 'STANDARD', PARSE_JSON('{"axle_class":"medium-heavy","beam_thickness_in":4,"gawr_lb":16000,"kingpin_size_in":2.25}') UNION ALL
    SELECT '151', 'Front Axle', 'Axle Assembly', 'Axle Rating', '18,000 lb Front Axle', 2800.00, 720.00, 'USA', 'Hauling', 3.5, 'Heavy-duty front axle.', 'PREMIUM', PARSE_JSON('{"axle_class":"heavy","beam_thickness_in":4.25,"gawr_lb":18000,"kingpin_size_in":2.5}') UNION ALL
    SELECT '152', 'Front Axle', 'Axle Assembly', 'Axle Rating', '20,000 lb Front Axle', 4200.00, 780.00, 'USA', 'Hauling', 4.5, 'Vocational heavy front.', 'PREMIUM', PARSE_JSON('{"axle_class":"vocational-heavy","beam_thickness_in":4.5,"gawr_lb":20000,"kingpin_size_in":2.5}') UNION ALL
    SELECT '153', 'Front Axle', 'Axle Assembly', 'Axle Rating', '22,000 lb Front Axle', 5500.00, 850.00, 'USA', 'Hauling', 5.0, 'Maximum front axle rating.', 'FLAGSHIP', PARSE_JSON('{"axle_class":"maximum","beam_thickness_in":5,"gawr_lb":22000,"kingpin_size_in":2.75}') UNION ALL
    SELECT '154', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Drum Brakes Standard', 0.00, 180.00, 'USA', 'Safety', 1.0, 'Conventional drum brakes.', 'ENTRY', PARSE_JSON('{"brake_class":"standard","brake_type":"drum","drum_diameter_in":15,"gawr_rating_lb":12000,"shoe_width_in":4}') UNION ALL
    SELECT '155', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Wide Drum Brakes', 350.00, 200.00, 'China', 'Safety', 2.0, 'Wider drums, more area.', 'STANDARD', PARSE_JSON('{"brake_class":"wide","brake_type":"drum","drum_diameter_in":16.5,"gawr_rating_lb":14000,"shoe_width_in":5}') UNION ALL
    SELECT '156', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Ventilated Drum Brakes', 450.00, 190.00, 'China', 'Safety', 2.5, 'Improved cooling drums.', 'STANDARD', PARSE_JSON('{"brake_class":"ventilated","brake_type":"drum","drum_diameter_in":16.5,"gawr_rating_lb":14000,"shoe_width_in":5}') UNION ALL
    SELECT '157', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Enhanced Drum Brakes', 650.00, 195.00, 'China', 'Safety', 3.5, 'Larger drum brakes with improved cooling.', 'STANDARD', PARSE_JSON('{"brake_class":"enhanced","brake_type":"drum","drum_diameter_in":16.5,"gawr_rating_lb":18000,"shoe_width_in":7}') UNION ALL
    SELECT '158', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Air Disc Brakes', 2800.00, 165.00, 'China', 'Safety', 4.0, 'Shorter stopping, fade resistance.', 'PREMIUM', PARSE_JSON('{"brake_class":"air-disc","brake_type":"disc","gawr_rating_lb":20000,"pad_area_sqin":42,"rotor_diameter_in":17}') UNION ALL
    SELECT '159', 'Front Axle', 'Front Brakes', 'Front Brake Type', 'Premium Air Disc System', 5500.00, 175.00, 'China', 'Safety', 5.0, 'High-performance disc brakes.', 'FLAGSHIP', PARSE_JSON('{"brake_class":"premium-disc","brake_type":"disc","gawr_rating_lb":23000,"pad_area_sqin":48,"rotor_diameter_in":17.7}') UNION ALL
    SELECT '160', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Tapered Leaf Spring', 0.00, 320.00, 'USA', 'Comfort', 1.0, 'Traditional leaf springs.', 'ENTRY', PARSE_JSON('{"ride_quality":"basic","shock_class":"standard","spring_rating_lb":12000,"suspension_type":"leaf"}') UNION ALL
    SELECT '161', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Heavy-Duty Leaf Spring', 650.00, 340.00, 'USA', 'Comfort', 2.0, 'Reinforced leaf springs.', 'STANDARD', PARSE_JSON('{"ride_quality":"firm","shock_class":"heavy-duty","spring_rating_lb":20000,"suspension_type":"leaf"}') UNION ALL
    SELECT '162', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Comfort-Ride Springs', 850.00, 295.00, 'USA', 'Comfort', 2.5, 'Optimized spring rate.', 'STANDARD', PARSE_JSON('{"ride_quality":"comfort","shock_class":"comfort","spring_rating_lb":14000,"suspension_type":"leaf"}') UNION ALL
    SELECT '163', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Parabolic Leaf Spring', 1200.00, 280.00, 'USA', 'Comfort', 3.5, 'Improved ride, lighter weight.', 'STANDARD', PARSE_JSON('{"ride_quality":"improved","shock_class":"standard","spring_rating_lb":16000,"suspension_type":"parabolic"}') UNION ALL
    SELECT '164', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Air-Ride Front Suspension', 4500.00, 350.00, 'USA', 'Comfort', 4.0, 'Superior ride quality.', 'PREMIUM', PARSE_JSON('{"ride_quality":"premium","shock_class":"air-ride","spring_rating_lb":18000,"suspension_type":"air"}') UNION ALL
    SELECT '165', 'Front Axle', 'Front Suspension', 'Front Suspension Type', 'Independent Air Suspension', 9500.00, 420.00, 'USA', 'Comfort', 5.0, 'Premium ride and handling.', 'FLAGSHIP', PARSE_JSON('{"ride_quality":"premium","shock_class":"heavy-duty","spring_rating_lb":25000,"suspension_type":"independent-air"}') UNION ALL
    SELECT '166', 'Front Axle', 'Steering', 'Steering Gear', 'Manual Steering Gear', 0.00, 85.00, 'USA', 'Safety', 1.0, 'Basic manual power steering.', 'ENTRY', PARSE_JSON('{"axle_capacity_lb":12000,"steering_class":"basic","steering_type":"manual","tie_rod_diameter_in":1.125}') UNION ALL
    SELECT '167', 'Front Axle', 'Steering', 'Steering Gear', 'Power Steering Standard', 950.00, 95.00, 'USA', 'Safety', 2.0, 'Hydraulic power steering.', 'STANDARD', PARSE_JSON('{"axle_capacity_lb":14000,"steering_class":"standard","steering_type":"hydraulic","tie_rod_diameter_in":1.25}') UNION ALL
    SELECT '168', 'Front Axle', 'Steering', 'Steering Gear', 'Heavy-Duty Power Steering', 1800.00, 100.00, 'Mexico', 'Safety', 3.0, 'High-capacity power steering.', 'STANDARD', PARSE_JSON('{"axle_capacity_lb":22000,"steering_class":"heavy-duty","steering_type":"hydraulic","tie_rod_diameter_in":1.625}') UNION ALL
    SELECT '169', 'Front Axle', 'Steering', 'Steering Gear', 'Variable-Assist Steering', 2500.00, 105.00, 'Mexico', 'Safety', 4.0, 'Speed-sensitive power assist.', 'PREMIUM', PARSE_JSON('{"axle_capacity_lb":18000,"steering_class":"premium","steering_type":"variable-assist","tie_rod_diameter_in":1.5}') UNION ALL
    SELECT '170', 'Front Axle', 'Steering', 'Steering Gear', 'Electronic Power Steering', 5500.00, 75.00, 'Mexico', 'Safety', 5.0, 'Lane-keeping assist compatible.', 'FLAGSHIP', PARSE_JSON('{"axle_capacity_lb":16000,"steering_class":"electronic","steering_type":"electronic","tie_rod_diameter_in":1.375}') UNION ALL
    SELECT '171', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Standard Drum Brakes', 0.00, 360.00, 'USA', 'Safety', 1.0, 'Standard S-cam drum brakes.', 'ENTRY', PARSE_JSON('{"brake_class":"standard","brake_type":"drum","drum_diameter_in":16.5,"gawr_rating_lb":23000,"shoe_width_in":5}') UNION ALL
    SELECT '172', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Wide-Track Drum Brakes', 550.00, 400.00, 'China', 'Safety', 2.0, 'Wider track drums.', 'STANDARD', PARSE_JSON('{"brake_class":"wide-track","brake_type":"drum","drum_diameter_in":16.5,"gawr_rating_lb":26000,"shoe_width_in":6}') UNION ALL
    SELECT '173', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Extended-Life Drum Brakes', 850.00, 385.00, 'China', 'Safety', 2.5, 'Automatic adjusters.', 'STANDARD', PARSE_JSON('{"brake_class":"extended-life","brake_type":"drum","drum_diameter_in":16.5,"gawr_rating_lb":30000,"shoe_width_in":7}') UNION ALL
    SELECT '174', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Heavy-Duty Drum Plus', 1200.00, 395.00, 'China', 'Safety', 3.5, 'Enhanced heavy-duty drums.', 'STANDARD', PARSE_JSON('{"brake_class":"heavy-duty","brake_type":"drum","drum_diameter_in":16.5,"gawr_rating_lb":40000,"shoe_width_in":8.625}') UNION ALL
    SELECT '175', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Air Disc Brakes Rear', 4500.00, 320.00, 'China', 'Safety', 4.0, 'Superior stopping power.', 'PREMIUM', PARSE_JSON('{"brake_class":"air-disc","brake_type":"disc","gawr_rating_lb":46000,"pad_area_sqin":48,"rotor_diameter_in":17}') UNION ALL
    SELECT '176', 'Rear Axle', 'Rear Brakes', 'Rear Brake Type', 'Full Air Disc System', 8500.00, 340.00, 'China', 'Safety', 5.0, 'Maximum performance.', 'FLAGSHIP', PARSE_JSON('{"brake_class":"full-disc","brake_type":"disc","gawr_rating_lb":52000,"pad_area_sqin":56,"rotor_diameter_in":17.7}') UNION ALL
    SELECT '177', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '2.85:1 Standard Ratio', 0.00, 0.00, 'USA', 'Economy', 2.0, 'Balanced for general freight.', 'STANDARD', PARSE_JSON('{"application":"highway","ratio":2.85,"ratio_class":"economy"}') UNION ALL
    SELECT '178', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '2.47:1 Economy Ratio', 150.00, 0.00, 'USA', 'Economy', 1.0, 'Tall gearing for max fuel economy.', 'ENTRY', PARSE_JSON('{"application":"highway","ratio":2.47,"ratio_class":"ultra-economy"}') UNION ALL
    SELECT '179', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '3.08:1 Balanced Ratio', 200.00, 0.00, 'USA', 'Economy', 2.5, 'Balanced gearing option.', 'STANDARD', PARSE_JSON('{"application":"mixed","ratio":3.08,"ratio_class":"balanced"}') UNION ALL
    SELECT '180', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '3.25:1 Performance Ratio', 350.00, 0.00, 'USA', 'Economy', 3.5, 'Better acceleration, hilly terrain.', 'PREMIUM', PARSE_JSON('{"application":"hilly","ratio":3.25,"ratio_class":"performance"}') UNION ALL
    SELECT '181', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '3.55:1 Vocational Ratio', 450.00, 0.00, 'USA', 'Economy', 4.0, 'Vocational applications.', 'PREMIUM', PARSE_JSON('{"application":"vocational","ratio":3.55,"ratio_class":"vocational"}') UNION ALL
    SELECT '182', 'Rear Axle', 'Rear Drive Assembly', 'Axle Ratio', '3.73:1 Heavy-Haul Ratio', 650.00, 0.00, 'USA', 'Economy', 5.0, 'Max pulling power.', 'FLAGSHIP', PARSE_JSON('{"application":"heavy-haul","ratio":3.73,"ratio_class":"heavy-haul"}') UNION ALL
    SELECT '183', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '4x2 Single Drive Axle', 0.00, 0.00, 'USA', 'Hauling', 1.0, 'Single drive axle, best economy.', 'ENTRY', PARSE_JSON('{"config":"4x2","drive_axles":1,"total_axles":2,"traction_class":"standard"}') UNION ALL
    SELECT '184', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '6x2 Tag Axle', 1800.00, 380.00, 'USA', 'Hauling', 2.0, 'Tag axle configuration.', 'STANDARD', PARSE_JSON('{"config":"6x2-tag","drive_axles":1,"total_axles":3,"traction_class":"standard"}') UNION ALL
    SELECT '185', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '6x2 Pusher Axle', 2500.00, 450.00, 'USA', 'Hauling', 3.0, 'Single drive with liftable pusher.', 'STANDARD', PARSE_JSON('{"config":"6x2-pusher","drive_axles":1,"total_axles":3,"traction_class":"improved"}') UNION ALL
    SELECT '186', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '6x4 Tandem Drive', 5500.00, 850.00, 'USA', 'Hauling', 4.0, 'Traditional tandem drive.', 'PREMIUM', PARSE_JSON('{"config":"6x4","drive_axles":2,"total_axles":3,"traction_class":"tandem"}') UNION ALL
    SELECT '187', 'Rear Axle', 'Rear Drive Assembly', 'Drive Configuration', '6x6 All-Wheel Drive', 15000.00, 1200.00, 'USA', 'Hauling', 5.0, 'Full AWD for severe conditions.', 'FLAGSHIP', PARSE_JSON('{"config":"6x6","drive_axles":3,"total_axles":3,"traction_class":"all-wheel"}') UNION ALL
    SELECT '188', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Basic ABS Only', 0.00, 25.00, 'USA', 'Safety', 1.0, 'Standard ABS.', 'ENTRY', PARSE_JSON('{"stability_control":false,"traction_level":1,"traction_type":"ABS-only"}') UNION ALL
    SELECT '189', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'ABS with Traction Control', 1500.00, 35.00, 'USA', 'Safety', 2.0, 'Improved starts in slippery conditions.', 'STANDARD', PARSE_JSON('{"stability_control":false,"traction_level":2,"traction_type":"ABS-TC"}') UNION ALL
    SELECT '190', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Limited-Slip Differential', 1800.00, 38.00, 'USA', 'Safety', 2.5, 'Mechanical limited slip.', 'STANDARD', PARSE_JSON('{"stability_control":false,"traction_level":2,"traction_type":"limited-slip"}') UNION ALL
    SELECT '191', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Differential Lock System', 2500.00, 42.00, 'USA', 'Safety', 3.5, 'Manual diff lock option.', 'STANDARD', PARSE_JSON('{"stability_control":false,"traction_level":3,"traction_type":"diff-lock"}') UNION ALL
    SELECT '192', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Advanced Traction System', 3500.00, 48.00, 'USA', 'Safety', 4.0, 'Full stability, rollover prevention.', 'PREMIUM', PARSE_JSON('{"stability_control":true,"traction_level":4,"traction_type":"advanced"}') UNION ALL
    SELECT '193', 'Rear Axle', 'Rear Drive Assembly', 'Traction Control', 'Full Electronic Stability', 6500.00, 65.00, 'USA', 'Safety', 5.0, 'Complete stability package.', 'FLAGSHIP', PARSE_JSON('{"stability_control":true,"traction_level":5,"traction_type":"full-ESC"}') UNION ALL
    SELECT '194', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Spring Rear Suspension', 0.00, 680.00, 'USA', 'Comfort', 1.0, 'Traditional multi-leaf springs.', 'ENTRY', PARSE_JSON('{"ride_quality":"basic","shock_class":"standard","spring_rating_lb":38000,"suspension_type":"spring"}') UNION ALL
    SELECT '195', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Vocational Spring Package', 1800.00, 720.00, 'USA', 'Comfort', 2.0, 'Heavy-duty vocational springs.', 'STANDARD', PARSE_JSON('{"ride_quality":"vocational","shock_class":"heavy-duty","spring_rating_lb":52000,"suspension_type":"spring"}') UNION ALL
    SELECT '196', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Air-Ride Rear Standard', 3500.00, 580.00, 'USA', 'Comfort', 2.5, 'Standard air-ride suspension.', 'STANDARD', PARSE_JSON('{"ride_quality":"standard","shock_class":"air-ride","spring_rating_lb":40000,"suspension_type":"air"}') UNION ALL
    SELECT '197', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Low-Ride Air Suspension', 4500.00, 600.00, 'Germany', 'Comfort', 3.5, 'Lowered ride height air system.', 'PREMIUM', PARSE_JSON('{"ride_quality":"low-ride","shock_class":"air-ride","spring_rating_lb":38000,"suspension_type":"air"}') UNION ALL
    SELECT '198', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Premium Air-Ride System', 6500.00, 620.00, 'USA', 'Comfort', 4.0, 'Adjustable ride height.', 'PREMIUM', PARSE_JSON('{"ride_quality":"premium","shock_class":"air-ride","spring_rating_lb":46000,"suspension_type":"air"}') UNION ALL
    SELECT '199', 'Rear Axle', 'Rear Suspension', 'Rear Suspension Type', 'Elite Air-Ride Package', 12000.00, 680.00, 'USA', 'Comfort', 5.0, 'Cab-coupled system.', 'FLAGSHIP', PARSE_JSON('{"ride_quality":"elite","shock_class":"heavy-duty","spring_rating_lb":52000,"suspension_type":"air"}') UNION ALL
    SELECT '200', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Standard Bias-Ply Tires', 0.00, 420.00, 'China', 'Economy', 1.0, 'Budget tires for light duty.', 'ENTRY', PARSE_JSON('{"fuel_efficiency":1,"load_rating":"G","tire_type":"bias-ply","tread_life_miles":50000}') UNION ALL
    SELECT '201', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Standard Radial Tires', 1200.00, 380.00, 'USA', 'Economy', 2.0, 'Quality radial tires.', 'STANDARD', PARSE_JSON('{"fuel_efficiency":2,"load_rating":"H","tire_type":"radial","tread_life_miles":80000}') UNION ALL
    SELECT '202', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'All-Season Regional Tires', 1800.00, 365.00, 'USA', 'Economy', 2.5, 'Regional all-season.', 'STANDARD', PARSE_JSON('{"fuel_efficiency":3,"load_rating":"H","tire_type":"all-season","tread_life_miles":100000}') UNION ALL
    SELECT '203', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Low-Rolling-Resistance Tires', 2800.00, 350.00, 'USA', 'Economy', 3.5, 'SmartWay verified, 3-5% fuel savings.', 'PREMIUM', PARSE_JSON('{"fuel_efficiency":5,"load_rating":"H","smartway_verified":true,"tire_type":"low-rolling","tread_life_miles":120000}') UNION ALL
    SELECT '204', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Wide-Base Single Tires', 3500.00, 290.00, 'Japan', 'Economy', 4.0, 'Super singles for fuel savings.', 'PREMIUM', PARSE_JSON('{"fuel_efficiency":5,"load_rating":"L","tire_type":"wide-base-single","tread_life_miles":90000}') UNION ALL
    SELECT '205', 'Rear Axle', 'Wheels & Tires', 'Tire Type', 'Premium Fuel-Max Tires', 4500.00, 340.00, 'USA', 'Economy', 5.0, 'Best-in-class fuel economy.', 'FLAGSHIP', PARSE_JSON('{"fuel_efficiency":6,"load_rating":"H","smartway_verified":true,"tire_type":"fuel-max","tread_life_miles":150000}') UNION ALL
    SELECT '206', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Steel Hub-Pilot Wheels', 0.00, 680.00, 'USA', 'Economy', 1.0, 'Standard steel wheels.', 'ENTRY', PARSE_JSON('{"wheel_class":"standard","wheel_type":"steel-hub-pilot","wheel_weight_lb":85}') UNION ALL
    SELECT '207', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Steel Disc Wheels', 450.00, 620.00, 'USA', 'Economy', 2.0, 'Improved steel disc wheels.', 'STANDARD', PARSE_JSON('{"wheel_class":"improved","wheel_type":"steel-disc","wheel_weight_lb":75}') UNION ALL
    SELECT '208', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Aluminum Disc Wheels', 1500.00, 480.00, 'USA', 'Economy', 2.5, 'Mid-range aluminum.', 'STANDARD', PARSE_JSON('{"wheel_class":"mid-range","wheel_type":"aluminum-disc","wheel_weight_lb":50}') UNION ALL
    SELECT '209', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Aluminum Wheels Standard', 2200.00, 420.00, 'China', 'Economy', 3.5, 'Forged aluminum, weight savings.', 'PREMIUM', PARSE_JSON('{"wheel_class":"premium","wheel_type":"forged-aluminum","wheel_weight_lb":42}') UNION ALL
    SELECT '210', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Premium Polished Aluminum', 4500.00, 380.00, 'China', 'Economy', 4.0, 'Mirror-polished, show quality.', 'FLAGSHIP', PARSE_JSON('{"wheel_class":"show","wheel_type":"polished-aluminum","wheel_weight_lb":45}') UNION ALL
    SELECT '211', 'Rear Axle', 'Wheels & Tires', 'Wheel Type', 'Forged Racing Wheels', 6500.00, 340.00, 'Germany', 'Economy', 5.0, 'Lightweight forged design.', 'FLAGSHIP', PARSE_JSON('{"wheel_class":"lightweight","wheel_type":"forged-racing","wheel_weight_lb":35}') UNION ALL
    SELECT '212', 'Safety', 'Active Safety', 'Stability Control', 'Basic ABS System', 0.00, 45.00, 'USA', 'Safety', 1.0, 'Standard 4-channel ABS.', 'ENTRY', PARSE_JSON('{"abs_channels":4,"rollover_protection":false,"stability_level":1}') UNION ALL
    SELECT '213', 'Safety', 'Active Safety', 'Stability Control', 'Enhanced ABS Plus', 950.00, 50.00, 'USA', 'Safety', 2.0, 'ABS with enhanced sensors.', 'STANDARD', PARSE_JSON('{"abs_channels":6,"rollover_protection":false,"stability_level":2}') UNION ALL
    SELECT '214', 'Safety', 'Active Safety', 'Stability Control', 'Roll Stability Control', 1800.00, 55.00, 'USA', 'Safety', 2.5, 'RSC prevents rollover.', 'STANDARD', PARSE_JSON('{"abs_channels":6,"rollover_protection":true,"stability_level":3}') UNION ALL
    SELECT '215', 'Safety', 'Active Safety', 'Stability Control', 'Trailer Stability Assist', 2500.00, 60.00, 'Germany', 'Safety', 3.5, 'Trailer sway control.', 'STANDARD', PARSE_JSON('{"abs_channels":6,"rollover_protection":true,"stability_level":3,"trailer_stability":true}') UNION ALL
    SELECT '216', 'Safety', 'Active Safety', 'Stability Control', 'Full Stability Control', 4500.00, 72.00, 'USA', 'Safety', 4.0, 'ESC with yaw control.', 'PREMIUM', PARSE_JSON('{"abs_channels":6,"rollover_protection":true,"stability_level":4,"yaw_control":true}') UNION ALL
    SELECT '217', 'Safety', 'Active Safety', 'Stability Control', 'Integrated Safety System', 8500.00, 95.00, 'USA', 'Safety', 5.0, 'ESC plus collision mitigation.', 'FLAGSHIP', PARSE_JSON('{"abs_channels":6,"collision_mitigation":true,"rollover_protection":true,"stability_level":5}') UNION ALL
    SELECT '218', 'Safety', 'Passive Safety', 'Mirror System', 'Manual West Coast Mirrors', 0.00, 25.00, 'USA', 'Safety', 1.0, 'Basic manual adjust.', 'ENTRY', PARSE_JSON('{"heated":false,"mirror_type":"manual","power":false}') UNION ALL
    SELECT '219', 'Safety', 'Passive Safety', 'Mirror System', 'Convex Spot Mirrors', 250.00, 28.00, 'USA', 'Safety', 2.0, 'Additional convex mirrors.', 'STANDARD', PARSE_JSON('{"heated":false,"mirror_type":"convex-spot","power":false}') UNION ALL
    SELECT '220', 'Safety', 'Passive Safety', 'Mirror System', 'Heated Power Mirrors', 650.00, 32.00, 'USA', 'Safety', 2.5, 'Electric adjust with heaters.', 'STANDARD', PARSE_JSON('{"heated":true,"mirror_type":"power-heated","power":true}') UNION ALL
    SELECT '221', 'Safety', 'Passive Safety', 'Mirror System', 'Power Fold Mirrors', 1200.00, 30.00, 'USA', 'Safety', 3.5, 'Electric fold with memory.', 'STANDARD', PARSE_JSON('{"heated":true,"memory":true,"mirror_type":"power-fold","power":true}') UNION ALL
    SELECT '222', 'Safety', 'Passive Safety', 'Mirror System', 'Aero Heated Mirrors', 1800.00, 28.00, 'USA', 'Safety', 4.0, 'Aerodynamic, reduced drag.', 'PREMIUM', PARSE_JSON('{"aerodynamic":true,"heated":true,"mirror_type":"aero-heated","power":true}') UNION ALL
    SELECT '223', 'Safety', 'Passive Safety', 'Mirror System', 'Camera Mirror System', 5500.00, 18.00, 'USA', 'Safety', 5.0, 'Digital displays, no blind spots.', 'FLAGSHIP', PARSE_JSON('{"blind_spot_free":true,"digital":true,"heated":false,"mirror_type":"camera","power":false}') UNION ALL
    SELECT '224', 'Transmission', 'Cooling', 'Transmission Cooler', 'Integrated Trans Cooler', 0.00, 15.00, 'USA', 'Cooling', 1.0, 'Basic in-radiator cooling.', 'ENTRY', PARSE_JSON('{"cooler_type":"integrated","cooling_capacity_btu":15000}') UNION ALL
    SELECT '225', 'Transmission', 'Cooling', 'Transmission Cooler', 'External Trans Cooler', 650.00, 25.00, 'USA', 'Cooling', 2.0, 'Separate external cooler.', 'STANDARD', PARSE_JSON('{"cooler_type":"external","cooling_capacity_btu":25000}') UNION ALL
    SELECT '226', 'Transmission', 'Cooling', 'Transmission Cooler', 'Auxiliary Trans Cooler', 950.00, 32.00, 'USA', 'Cooling', 2.5, 'Additional cooling capacity.', 'STANDARD', PARSE_JSON('{"cooler_type":"auxiliary","cooling_capacity_btu":35000}') UNION ALL
    SELECT '227', 'Transmission', 'Cooling', 'Transmission Cooler', 'Stacked-Plate Cooler', 1200.00, 30.00, 'USA', 'Cooling', 3.5, 'Efficient stacked-plate design.', 'STANDARD', PARSE_JSON('{"cooler_type":"stacked-plate","cooling_capacity_btu":40000}') UNION ALL
    SELECT '228', 'Transmission', 'Cooling', 'Transmission Cooler', 'Heavy-Duty Trans Cooler', 1500.00, 38.00, 'USA', 'Cooling', 4.0, 'Large cooler with thermostat.', 'PREMIUM', PARSE_JSON('{"cooler_type":"heavy-duty","cooling_capacity_btu":55000}') UNION ALL
    SELECT '229', 'Transmission', 'Cooling', 'Transmission Cooler', 'Maximum Cooling Package', 3500.00, 55.00, 'USA', 'Cooling', 5.0, 'Oversized cooler with fan.', 'FLAGSHIP', PARSE_JSON('{"cooler_type":"maximum","cooling_capacity_btu":75000}') UNION ALL
    SELECT '230', 'Transmission', 'PTO System', 'PTO Configuration', 'No PTO Provision', 0.00, 0.00, 'USA', 'Hauling', 1.0, 'Linehaul without PTO.', 'ENTRY', PARSE_JSON('{"pto_hp":0,"pto_type":"none"}') UNION ALL
    SELECT '231', 'Transmission', 'PTO System', 'PTO Configuration', 'Single PTO Opening', 450.00, 15.00, 'USA', 'Hauling', 2.0, 'Single-speed output.', 'STANDARD', PARSE_JSON('{"pto_hp":50,"pto_type":"single"}') UNION ALL
    SELECT '232', 'Transmission', 'PTO System', 'PTO Configuration', 'Dual PTO System', 1500.00, 35.00, 'USA', 'Hauling', 2.5, 'Front and rear PTO.', 'PREMIUM', PARSE_JSON('{"pto_hp":100,"pto_type":"dual"}') UNION ALL
    SELECT '233', 'Transmission', 'PTO System', 'PTO Configuration', 'Live PTO System', 2200.00, 45.00, 'USA', 'Hauling', 3.5, 'Always-engaged PTO.', 'PREMIUM', PARSE_JSON('{"pto_hp":75,"pto_type":"live"}') UNION ALL
    SELECT '234', 'Transmission', 'PTO System', 'PTO Configuration', 'Hydraulic PTO Package', 2800.00, 55.00, 'USA', 'Hauling', 4.0, 'Full hydraulic PTO system.', 'PREMIUM', PARSE_JSON('{"pto_hp":120,"pto_type":"hydraulic"}') UNION ALL
    SELECT '235', 'Transmission', 'PTO System', 'PTO Configuration', 'Heavy-Duty PTO Package', 3500.00, 65.00, 'USA', 'Hauling', 5.0, 'Maximum PTO capacity.', 'FLAGSHIP', PARSE_JSON('{"pto_hp":180,"pto_type":"heavy-duty"}') UNION ALL
    SELECT '236', 'Transmission', 'Transmission Assembly', 'Clutch System', 'Standard 14-inch Clutch', 0.00, 95.00, 'USA', 'Durability', 1.0, 'Basic 14-inch single plate.', 'ENTRY', PARSE_JSON('{"clutch_class":"standard","clutch_diameter_in":14,"torque_capacity_lb_ft":1100}') UNION ALL
    SELECT '237', 'Transmission', 'Transmission Assembly', 'Clutch System', '14-inch Heavy-Duty Clutch', 450.00, 105.00, 'USA', 'Durability', 2.0, 'Enhanced 14-inch clutch.', 'STANDARD', PARSE_JSON('{"clutch_class":"heavy-duty","clutch_diameter_in":14,"torque_capacity_lb_ft":1400}') UNION ALL
    SELECT '238', 'Transmission', 'Transmission Assembly', 'Clutch System', '15.5-inch Standard Clutch', 650.00, 115.00, 'USA', 'Durability', 2.5, 'Standard Class 8 clutch.', 'STANDARD', PARSE_JSON('{"clutch_class":"standard","clutch_diameter_in":15.5,"torque_capacity_lb_ft":1650}') UNION ALL
    SELECT '239', 'Transmission', 'Transmission Assembly', 'Clutch System', '15.5-inch Heavy-Duty Clutch', 1800.00, 125.00, 'USA', 'Durability', 3.5, 'Higher torque rating.', 'PREMIUM', PARSE_JSON('{"clutch_class":"heavy-duty","clutch_diameter_in":15.5,"torque_capacity_lb_ft":1850}') UNION ALL
    SELECT '240', 'Transmission', 'Transmission Assembly', 'Clutch System', 'Ceramic Heavy Clutch', 2500.00, 135.00, 'Germany', 'Durability', 4.0, 'Ceramic friction material.', 'PREMIUM', PARSE_JSON('{"clutch_class":"ceramic","clutch_diameter_in":15.5,"torque_capacity_lb_ft":2100}') UNION ALL
    SELECT '241', 'Transmission', 'Transmission Assembly', 'Clutch System', 'Auto-Adjust Heavy Clutch', 3500.00, 145.00, 'USA', 'Durability', 5.0, 'Self-adjusting, extended life.', 'FLAGSHIP', PARSE_JSON('{"clutch_class":"auto-adjust","clutch_diameter_in":15.5,"torque_capacity_lb_ft":2200}') UNION ALL
    SELECT '242', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Direct Drive Overdrive', 0.00, 0.00, 'USA', 'Economy', 1.0, 'Fuel economy focus.', 'ENTRY', PARSE_JSON('{"gear_spread":12.8,"overdrive":true,"ratio_type":"direct-drive"}') UNION ALL
    SELECT '243', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Overdrive Transmission', 450.00, 0.00, 'USA', 'Economy', 2.0, 'Balance of economy and performance.', 'STANDARD', PARSE_JSON('{"gear_spread":14.2,"overdrive":true,"ratio_type":"overdrive"}') UNION ALL
    SELECT '244', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Economy Plus Ratios', 650.00, 0.00, 'USA', 'Economy', 2.5, 'Fuel-optimized gear spread.', 'STANDARD', PARSE_JSON('{"gear_spread":11.5,"overdrive":true,"ratio_type":"economy-plus"}') UNION ALL
    SELECT '245', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Close-Ratio Performance', 850.00, 0.00, 'USA', 'Economy', 3.5, 'Close-ratio for performance.', 'STANDARD', PARSE_JSON('{"gear_spread":9.8,"overdrive":false,"ratio_type":"close-ratio"}') UNION ALL
    SELECT '246', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Wide-Range Ratios', 1200.00, 0.00, 'USA', 'Economy', 4.0, 'Expanded ratio coverage.', 'PREMIUM', PARSE_JSON('{"gear_spread":16.5,"overdrive":true,"ratio_type":"wide-range"}') UNION ALL
    SELECT '247', 'Transmission', 'Transmission Assembly', 'Gear Ratios', 'Deep-Reduction Heavy-Haul', 2500.00, 0.00, 'USA', 'Economy', 5.0, 'Maximum ratio spread.', 'FLAGSHIP', PARSE_JSON('{"gear_spread":18.2,"overdrive":true,"ratio_type":"deep-reduction"}') UNION ALL
    SELECT '248', 'Transmission', 'Transmission Assembly', 'Transmission Type', '10-Speed Manual', 0.00, 450.00, 'USA', 'Economy', 2.0, 'Basic 10-speed manual.', 'ENTRY', PARSE_JSON('{"gear_count":10,"torque_rating_lb_ft":1400,"trans_class":"basic","trans_type":"manual"}') UNION ALL
    SELECT '249', 'Transmission', 'Transmission Assembly', 'Transmission Type', '9-Speed Economy', 200.00, 420.00, 'USA', 'Economy', 1.0, 'Entry 9-speed manual.', 'ENTRY', PARSE_JSON('{"gear_count":9,"torque_rating_lb_ft":1100,"trans_class":"economy","trans_type":"manual"}') UNION ALL
    SELECT '250', 'Transmission', 'Transmission Assembly', 'Transmission Type', '13-Speed Manual', 1800.00, 485.00, 'USA', 'Economy', 2.5, 'Traditional 13-speed.', 'STANDARD', PARSE_JSON('{"gear_count":13,"torque_rating_lb_ft":1650,"trans_class":"traditional","trans_type":"manual"}') UNION ALL
    SELECT '251', 'Transmission', 'Transmission Assembly', 'Transmission Type', '10-Speed Automated', 3200.00, 495.00, 'USA', 'Economy', 3.5, '10-speed AMT option.', 'STANDARD', PARSE_JSON('{"gear_count":10,"torque_rating_lb_ft":1850,"trans_class":"AMT","trans_type":"automated"}') UNION ALL
    SELECT '252', 'Transmission', 'Transmission Assembly', 'Transmission Type', '12-Speed Automated Manual', 4500.00, 520.00, 'USA', 'Economy', 4.0, 'AMT with driver choice.', 'PREMIUM', PARSE_JSON('{"gear_count":12,"torque_rating_lb_ft":2050,"trans_class":"AMT-premium","trans_type":"automated"}') UNION ALL
    SELECT '253', 'Transmission', 'Transmission Assembly', 'Transmission Type', '18-Speed Automatic', 8500.00, 580.00, 'Japan', 'Economy', 5.0, 'Full automatic with torque converter.', 'FLAGSHIP', PARSE_JSON('{"gear_count":18,"torque_rating_lb_ft":2200,"trans_class":"full-auto","trans_type":"automatic"}')
);

