-- Digital Twin Truck Configurator - App Tables & Services
-- Creates tables for saved configs, chat history, engineering docs, and validation rules
-- Run after 02_data.sql

USE SCHEMA BOM.BOM4;

CREATE TABLE IF NOT EXISTS SAVED_CONFIGS (
    CONFIG_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    MODEL_ID VARCHAR(50) NOT NULL,
    CONFIG_NAME VARCHAR(200),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TOTAL_COST_USD NUMBER(12,2) DEFAULT 0,
    TOTAL_WEIGHT_LBS NUMBER(12,2) DEFAULT 0,
    CONFIG_OPTIONS VARIANT,
    PERFORMANCE_SUMMARY VARIANT,
    NOTES VARCHAR(4000),
    IS_VALIDATED BOOLEAN DEFAULT FALSE,
    CREATED_BY VARCHAR(200) DEFAULT 'User'
);

CREATE TABLE IF NOT EXISTS CHAT_HISTORY (
    CHAT_ID VARCHAR(50) NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    SESSION_ID VARCHAR(50) NOT NULL,
    MODEL_ID VARCHAR(50) NOT NULL,
    CONFIG_ID VARCHAR(50),
    MESSAGE_ROLE VARCHAR(20) NOT NULL,
    MESSAGE_CONTENT VARCHAR(16777216) NOT NULL,
    OPTIMIZATION_APPLIED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ENGINEERING_DOCS_CHUNKED (
    CHUNK_ID VARCHAR(50) DEFAULT UUID_STRING(),
    DOC_ID VARCHAR(100),
    DOC_TITLE VARCHAR(500),
    DOC_PATH VARCHAR(500),
    CHUNK_INDEX NUMBER,
    CHUNK_TEXT VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LINKED_PARTS VARIANT,
    CACHED_REQUIREMENTS VARIANT
);

ALTER TABLE ENGINEERING_DOCS_CHUNKED SET CHANGE_TRACKING = TRUE;

CREATE TABLE IF NOT EXISTS VALIDATION_RULES (
    RULE_ID VARCHAR(50) NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    DOC_ID VARCHAR(100) NOT NULL,
    DOC_TITLE VARCHAR(500),
    LINKED_OPTION_ID VARCHAR(50),
    COMPONENT_GROUP VARCHAR(100) NOT NULL,
    SPEC_NAME VARCHAR(100) NOT NULL,
    MIN_VALUE NUMBER(38,2),
    MAX_VALUE NUMBER(38,2),
    UNIT VARCHAR(50),
    RAW_REQUIREMENT VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE CORTEX SEARCH SERVICE IF NOT EXISTS ENGINEERING_DOCS_SEARCH
    ON CHUNK_TEXT
    ATTRIBUTES DOC_ID, DOC_TITLE, DOC_PATH, CHUNK_INDEX
    WAREHOUSE = __WAREHOUSE__
    TARGET_LAG = '1 minute'
    AS (
        SELECT CHUNK_ID, DOC_ID, DOC_TITLE, DOC_PATH, CHUNK_INDEX, CHUNK_TEXT
        FROM ENGINEERING_DOCS_CHUNKED
    );
