-- Digital Twin Truck Configurator - Semantic View Setup
-- Run after 02c_truck_options.sql

USE SCHEMA BOM.BOM4;

-- ============================================
-- Create Semantic View for Cortex Analyst
-- ============================================

CREATE OR REPLACE SEMANTIC VIEW TRUCK_CONFIG_ANALYST_V2
  TABLES (
    TRUCK_MODELS AS BOM.BOM4.MODEL_TBL PRIMARY KEY (MODEL_ID) COMMENT='Available truck models',
    BOM_OPTIONS AS BOM.BOM4.BOM_TBL PRIMARY KEY (OPTION_ID) COMMENT='Bill of Materials options',
    MODEL_VALID_OPTIONS AS BOM.BOM4.TRUCK_OPTIONS COMMENT='Links models to valid options'
  )
  RELATIONSHIPS (
    VALID_OPTIONS_TO_BOM AS MODEL_VALID_OPTIONS(OPTION_ID) REFERENCES BOM_OPTIONS(OPTION_ID),
    VALID_OPTIONS_TO_MODELS AS MODEL_VALID_OPTIONS(MODEL_ID) REFERENCES TRUCK_MODELS(MODEL_ID)
  )
  FACTS (
    TRUCK_MODELS.BASE_MSRP AS BASE_MSRP,
    TRUCK_MODELS.BASE_WEIGHT AS BASE_WEIGHT_LBS,
    BOM_OPTIONS.COST_USD AS COST_USD WITH SYNONYMS=('cost','price'),
    BOM_OPTIONS.WEIGHT_LBS AS WEIGHT_LBS,
    BOM_OPTIONS.PERFORMANCE_SCORE AS PERFORMANCE_SCORE WITH SYNONYMS=('score','rating')
  )
  DIMENSIONS (
    TRUCK_MODELS.MODEL_ID AS MODEL_ID WITH SYNONYMS=('model','truck'),
    TRUCK_MODELS.MODEL_NAME AS MODEL_NM,
    BOM_OPTIONS.OPTION_ID AS OPTION_ID,
    BOM_OPTIONS.SYSTEM_NAME AS SYSTEM_NM,
    BOM_OPTIONS.SUBSYSTEM_NAME AS SUBSYSTEM_NM,
    BOM_OPTIONS.COMPONENT_GROUP AS COMPONENT_GROUP,
    BOM_OPTIONS.OPTION_NAME AS OPTION_NM,
    BOM_OPTIONS.PERFORMANCE_CATEGORY AS PERFORMANCE_CATEGORY WITH SYNONYMS=('category','optimize for','maximize'),
    MODEL_VALID_OPTIONS.MODEL_ID AS MODEL_ID,
    MODEL_VALID_OPTIONS.OPTION_ID AS OPTION_ID,
    MODEL_VALID_OPTIONS.IS_DEFAULT AS IS_DEFAULT
  )
  COMMENT='Truck configuration optimization semantic model'
  AI_SQL_GENERATION 'CRITICAL RULES: 1. ALL queries MUST include OPTION_ID in SELECT 2. MODEL_ID values are: MDL-REGIONAL, MDL-FLEET, MDL-LONGHAUL, MDL-HEAVYHAUL, MDL-PREMIUM 3. When user says Regional use MODEL_ID=''MDL-REGIONAL'' 4. PERFORMANCE_CATEGORY values: Safety, Comfort, Power, Economy, Hauling, Durability, Cooling, Emissions 5. For multi-category optimization (maximize X and Y while minimizing cost):
   - For categories to maximize: ORDER BY PERFORMANCE_SCORE DESC
   - For other categories: ORDER BY COST_USD ASC
   - Use QUALIFY ROW_NUMBER() OVER (PARTITION BY COMPONENT_GROUP...) = 1 '
  WITH EXTENSION (CA='{"tables":[{"name":"TRUCK_MODELS","dimensions":[{"name":"MODEL_ID","unique":true},{"name":"MODEL_NAME"}],"facts":[{"name":"BASE_MSRP"},{"name":"BASE_WEIGHT"}]},{"name":"BOM_OPTIONS","dimensions":[{"name":"OPTION_ID","unique":true},{"name":"SYSTEM_NAME"},{"name":"SUBSYSTEM_NAME"},{"name":"COMPONENT_GROUP"},{"name":"OPTION_NAME"},{"name":"PERFORMANCE_CATEGORY"}],"facts":[{"name":"COST_USD"},{"name":"WEIGHT_LBS"},{"name":"PERFORMANCE_SCORE"}]},{"name":"MODEL_VALID_OPTIONS","dimensions":[{"name":"MODEL_ID"},{"name":"OPTION_ID"},{"name":"IS_DEFAULT"}]}],"relationships":[{"name":"valid_options_to_models","join_type":"inner"},{"name":"valid_options_to_bom","join_type":"inner"}],"verified_queries":[{"name":"vqr_maximize_safety_comfort_minimize_cost","sql":"WITH ranked_options AS (\\n  SELECT \\n    b.OPTION_ID, b.OPTION_NM, b.COMPONENT_GROUP, b.COST_USD, b.WEIGHT_LBS,\\n    b.PERFORMANCE_CATEGORY, b.PERFORMANCE_SCORE,\\n    CASE WHEN b.PERFORMANCE_CATEGORY IN (''Safety'', ''Comfort'') \\n         THEN ROW_NUMBER() OVER (PARTITION BY b.COMPONENT_GROUP ORDER BY b.PERFORMANCE_SCORE DESC)\\n         ELSE ROW_NUMBER() OVER (PARTITION BY b.COMPONENT_GROUP ORDER BY b.COST_USD ASC)\\n    END AS rn\\n  FROM BOM.BOM4.TRUCK_OPTIONS v\\n  JOIN BOM.BOM4.BOM_TBL b ON v.OPTION_ID = b.OPTION_ID\\n  WHERE v.MODEL_ID = ''MDL-REGIONAL''\\n)\\nSELECT OPTION_ID, OPTION_NM, COMPONENT_GROUP, COST_USD, WEIGHT_LBS, PERFORMANCE_CATEGORY, PERFORMANCE_SCORE\\nFROM ranked_options WHERE rn = 1\\n","question":"For MDL-REGIONAL maximize safety and comfort while minimizing all other costs"},{"name":"vqr_maximize_hauling_regional","sql":"SELECT b.OPTION_ID, b.COMPONENT_GROUP, b.OPTION_NM, b.PERFORMANCE_CATEGORY, b.PERFORMANCE_SCORE, b.COST_USD, b.WEIGHT_LBS\\nFROM BOM.BOM4.MODEL_TBL m\\nJOIN BOM.BOM4.TRUCK_OPTIONS v ON m.MODEL_ID = v.MODEL_ID\\nJOIN BOM.BOM4.BOM_TBL b ON v.OPTION_ID = b.OPTION_ID\\nWHERE m.MODEL_ID = ''MDL-REGIONAL'' AND b.PERFORMANCE_CATEGORY = ''Hauling''\\nQUALIFY ROW_NUMBER() OVER (PARTITION BY b.COMPONENT_GROUP ORDER BY b.PERFORMANCE_SCORE DESC) = 1\\nORDER BY b.PERFORMANCE_SCORE DESC\\n","question":"How can I maximize hauling for the Regional Hauler?"},{"name":"vqr_maximize_safety_regional","sql":"SELECT b.OPTION_ID, b.COMPONENT_GROUP, b.OPTION_NM, b.PERFORMANCE_CATEGORY, b.PERFORMANCE_SCORE, b.COST_USD, b.WEIGHT_LBS\\nFROM BOM.BOM4.MODEL_TBL m\\nJOIN BOM.BOM4.TRUCK_OPTIONS v ON m.MODEL_ID = v.MODEL_ID\\nJOIN BOM.BOM4.BOM_TBL b ON v.OPTION_ID = b.OPTION_ID\\nWHERE m.MODEL_ID = ''MDL-REGIONAL'' AND b.PERFORMANCE_CATEGORY = ''Safety''\\nQUALIFY ROW_NUMBER() OVER (PARTITION BY b.COMPONENT_GROUP ORDER BY b.PERFORMANCE_SCORE DESC) = 1\\nORDER BY b.PERFORMANCE_SCORE DESC\\n","question":"How can I maximize safety for the Regional Hauler?"},{"name":"vqr_maximize_comfort_regional","sql":"SELECT b.OPTION_ID, b.COMPONENT_GROUP, b.OPTION_NM, b.PERFORMANCE_CATEGORY, b.PERFORMANCE_SCORE, b.COST_USD, b.WEIGHT_LBS\\nFROM BOM.BOM4.MODEL_TBL m\\nJOIN BOM.BOM4.TRUCK_OPTIONS v ON m.MODEL_ID = v.MODEL_ID\\nJOIN BOM.BOM4.BOM_TBL b ON v.OPTION_ID = b.OPTION_ID\\nWHERE m.MODEL_ID = ''MDL-REGIONAL'' AND b.PERFORMANCE_CATEGORY = ''Comfort''\\nQUALIFY ROW_NUMBER() OVER (PARTITION BY b.COMPONENT_GROUP ORDER BY b.PERFORMANCE_SCORE DESC) = 1\\nORDER BY b.PERFORMANCE_SCORE DESC\\n","question":"How can I maximize comfort for the Regional Hauler?"},{"name":"vqr_maximize_power_regional","sql":"SELECT b.OPTION_ID, b.COMPONENT_GROUP, b.OPTION_NM, b.PERFORMANCE_CATEGORY, b.PERFORMANCE_SCORE, b.COST_USD, b.WEIGHT_LBS\\nFROM BOM.BOM4.MODEL_TBL m\\nJOIN BOM.BOM4.TRUCK_OPTIONS v ON m.MODEL_ID = v.MODEL_ID\\nJOIN BOM.BOM4.BOM_TBL b ON v.OPTION_ID = b.OPTION_ID\\nWHERE m.MODEL_ID = ''MDL-REGIONAL'' AND b.PERFORMANCE_CATEGORY = ''Power''\\nQUALIFY ROW_NUMBER() OVER (PARTITION BY b.COMPONENT_GROUP ORDER BY b.PERFORMANCE_SCORE DESC) = 1\\nORDER BY b.PERFORMANCE_SCORE DESC\\n","question":"How can I maximize power for the Regional Hauler?"},{"name":"vqr_minimize_all_costs_regional","sql":"SELECT b.OPTION_ID, b.COMPONENT_GROUP, b.OPTION_NM, b.PERFORMANCE_CATEGORY, b.PERFORMANCE_SCORE, b.COST_USD, b.WEIGHT_LBS\\nFROM BOM.BOM4.MODEL_TBL m\\nJOIN BOM.BOM4.TRUCK_OPTIONS v ON m.MODEL_ID = v.MODEL_ID\\nJOIN BOM.BOM4.BOM_TBL b ON v.OPTION_ID = b.OPTION_ID\\nWHERE m.MODEL_ID = ''MDL-REGIONAL''\\nQUALIFY ROW_NUMBER() OVER (PARTITION BY b.COMPONENT_GROUP ORDER BY b.COST_USD ASC) = 1\\nORDER BY b.COST_USD ASC\\n","question":"Minimize all costs for the Regional Hauler"}]}');

-- Verify semantic view
SHOW SEMANTIC VIEWS IN SCHEMA BOM.BOM4;
